/**
 * Two-Pass LilyPond Generation with Composer Planning
 * Pass A: Generate structured composer plan (JSON)
 * Pass B: Generate LilyPond from plan
 */

import Anthropic from '@anthropic-ai/sdk';
import { compileLilyPond, writeLilyPondFile } from './lilypondCompiler.js';
import { getStylePreset, getComposerInspiration } from './stylePresets.js';
import { validateMidi, getValidationReport } from './midiValidator.js';
import { renderAudio } from './audioRenderer.js';
import { analyzeHumanLikeness } from './humanMetrics.js';
import { generateCacheKey, getCachedResult, getCachedPlan, saveCacheEntry } from './cache.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Anthropic client
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY
});

const MAX_REPAIR_ATTEMPTS = 3;
const MAX_PLAN_PARSE_ATTEMPTS = 2;
const MAX_TOTAL_CLAUDE_CALLS = 10;  // Safety guard: max API calls per job

/**
 * Safety guard: Check if we've exceeded max API calls
 */
function checkAPICallLimit(costTracking) {
  if (costTracking.totalCalls >= MAX_TOTAL_CLAUDE_CALLS) {
    throw new Error(
      `Safety limit exceeded: job reached ${MAX_TOTAL_CLAUDE_CALLS} API calls. ` +
      `This prevents runaway costs. Adjust MAX_TOTAL_CLAUDE_CALLS if needed.`
    );
  }
}

/**
 * Cost tracking helper
 * Approximate tokens: chars / 4 (rough estimate)
 */
function trackAPICall(costTracking, callType, requestChars, responseChars) {
  const approxInputTokens = Math.ceil(requestChars / 4);
  const approxOutputTokens = Math.ceil(responseChars / 4);

  costTracking.calls.push({
    type: callType,
    requestChars,
    responseChars,
    approxInputTokens,
    approxOutputTokens
  });

  costTracking.totalCalls++;
  costTracking.totalInputTokens += approxInputTokens;
  costTracking.totalOutputTokens += approxOutputTokens;
}

/**
 * Initialize cost tracking object
 */
function createCostTracking() {
  return {
    calls: [],
    totalCalls: 0,
    totalInputTokens: 0,
    totalOutputTokens: 0
  };
}

/**
 * Normalize free text to keep prompts concise and token-efficient.
 */
function compactPromptText(text, maxLength = 240) {
  if (!text || typeof text !== 'string') return '';

  const compact = text.replace(/\s+/g, ' ').trim();
  if (compact.length <= maxLength) return compact;

  return compact.slice(0, maxLength - 3).trimEnd() + '...';
}

/**
 * Build provenance markup block for LilyPond PDF.
 * Appears as a small, muted info block above the score.
 */
function buildProvenanceMarkup(params) {
  const { key, bars, difficulty, style, inspiredBy, prompt } = params;

  const year = new Date().getFullYear();
  const diffLabel = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);

  // Escape for LilyPond string literals
  function escapeLy(str) {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  // Truncate prompt if needed
  let shortPrompt = (prompt || '').trim();
  if (shortPrompt.length > 120) {
    shortPrompt = shortPrompt.substring(0, 117).trim() + '...';
  }

  // Get display names for style and composer
  const styleName = style ? (getStylePreset(style)?.name || style) : null;
  const composerName = inspiredBy ? (getComposerInspiration(inspiredBy)?.name || inspiredBy) : null;

  // Build content lines for the markup block
  const lines = [];

  if (shortPrompt) {
    lines.push('"Generated from a natural-language description:"');
    lines.push('\\italic { "' + escapeLy('\u201C' + shortPrompt + '\u201D') + '" }');
    lines.push('\\vspace #0.3');
  }

  lines.push('"Key: ' + escapeLy(key) + ' \u00B7 Bars: ' + bars + ' \u00B7 Difficulty: ' + diffLabel + '"');

  if (styleName) {
    lines.push('"Style: ' + escapeLy(styleName) + '"');
  }
  if (composerName) {
    lines.push('"Inspiration: ' + escapeLy(composerName) + '"');
  }

  lines.push('\\vspace #0.3');
  lines.push('"Generated by Prelude \u00B7 ' + year + '"');

  const indented = lines.map(l => '      ' + l).join('\n');

  return [
    '',
    '\\markup \\fill-line {',
    '  \\center-column {',
    "    \\fontsize #-2 \\with-color #(x11-color 'grey50) \\center-column {",
    indented,
    '    }',
    '    \\vspace #1',
    '  }',
    '}',
    ''
  ].join('\n');
}

/**
 * Inject provenance markup into LilyPond code, before the \\score block.
 */
function injectProvenance(code, provenanceMarkup) {
  const scoreIndex = code.indexOf('\\score');
  if (scoreIndex !== -1) {
    return code.substring(0, scoreIndex) + provenanceMarkup + '\n' + code.substring(scoreIndex);
  }
  // Fallback: prepend after version line
  const versionEnd = code.indexOf('\n');
  if (versionEnd !== -1) {
    return code.substring(0, versionEnd + 1) + provenanceMarkup + '\n' + code.substring(versionEnd + 1);
  }
  return provenanceMarkup + '\n' + code;
}

/**
 * Detect active behavioral mode flags for a given params object.
 * Returns { baroque, jazz, organicTime, antiEtude } booleans.
 * Low threshold — better to over-trigger than under-trigger.
 */
export function getModeFlags(params) {
  const { style, inspiredBy, prompt } = params;

  // Baroque detection
  let baroque = false;
  if (style && ['baroque', 'keyboard', 'partita'].includes(style.toLowerCase())) baroque = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'bach') baroque = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const baroqueKeywords = [
      'bach', 'partita', 'fugue', 'invention', 'baroque', 'contrapuntal',
      'counterpoint', 'prelude and fugue', 'well-tempered', 'toccata',
      'sarabande', 'allemande', 'courante', 'gigue', 'bourrée', 'bourree',
      'gavotte', 'minuet', 'passacaglia', 'chaconne', 'ricercar', 'sinfonia'
    ];
    if (baroqueKeywords.some(k => lower.includes(k))) baroque = true;
  }

  // Jazz detection
  let jazz = false;
  if (style && style.toLowerCase() === 'jazz-tinged') jazz = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'gershwin') jazz = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const jazzKeywords = [
      'jazz', 'swing', 'bebop', 'blues', 'groove', 'groovy', 'funky',
      'syncopat', 'boogie', 'stride', 'ragtime', 'soul', 'bossa', 'latin jazz'
    ];
    if (jazzKeywords.some(k => lower.includes(k))) jazz = true;
  }

  // Impressionist detection
  let impressionist = false;
  if (style && style.toLowerCase() === 'impressionist') impressionist = true;
  if (inspiredBy && ['debussy', 'ravel'].includes(inspiredBy.toLowerCase())) impressionist = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const impressionistKeywords = [
      'impressionist', 'debussy', 'ravel', 'clair de lune', 'claire de lune',
      'whole tone', 'impressionism', 'arabesques', 'reverie', 'rêverie', 'nocturne'
    ];
    if (impressionistKeywords.some(k => lower.includes(k))) impressionist = true;
  }

  // Classical detection (Mozart, Haydn)
  let classical = false;
  if (style && style.toLowerCase() === 'classical') classical = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'mozart') classical = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const classicalKeywords = [
      'mozart', 'haydn', 'classical', 'alberti', 'sonata', 'sonatina',
      'minuet and trio', 'rondo', 'periodic', 'galant'
    ];
    if (classicalKeywords.some(k => lower.includes(k))) classical = true;
  }

  // Romantic detection (Chopin, Schubert, Schumann)
  let romantic = false;
  if (style && style.toLowerCase() === 'romantic') romantic = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'chopin') romantic = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const romanticKeywords = [
      'chopin', 'romantic', 'cantabile', 'lyrical', 'nocturne style',
      'schubert', 'schumann', 'liszt', 'singing melody', 'expressive rubato'
    ];
    if (romanticKeywords.some(k => lower.includes(k))) romantic = true;
  }

  // Minimal detection (Glass, ambient, minimalist)
  let minimal = false;
  if (style && style.toLowerCase() === 'minimal') minimal = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'glass') minimal = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const minimalKeywords = [
      'glass', 'minimal', 'minimalist', 'ambient', 'ostinato', 'repetit',
      'hypnotic', 'drone', 'meditative', 'arvo pärt', 'part', 'satie'
    ];
    if (minimalKeywords.some(k => lower.includes(k))) minimal = true;
  }

  // Cinematic detection (Zimmer, film score)
  let cinematic = false;
  if (style && style.toLowerCase() === 'cinematic') cinematic = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'zimmer') cinematic = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const cinematicKeywords = [
      'zimmer', 'cinematic', 'film score', 'soundtrack', 'epic', 'cinematic build',
      'nils frahm', 'ludovico', 'yann tiersen', 'movie music', 'trailer'
    ];
    if (cinematicKeywords.some(k => lower.includes(k))) cinematic = true;
  }

  // Baroque takes priority over everything
  if (baroque) { jazz = false; impressionist = false; classical = false; romantic = false; minimal = false; cinematic = false; }
  // Prevent style conflicts (first detected wins after baroque)
  if (jazz) { impressionist = false; classical = false; romantic = false; minimal = false; cinematic = false; }
  if (impressionist) { classical = false; romantic = false; minimal = false; cinematic = false; }
  if (classical) { romantic = false; minimal = false; cinematic = false; }
  if (romantic) { minimal = false; cinematic = false; }
  if (minimal) { cinematic = false; }

  return {
    baroque,
    jazz,
    impressionist,
    classical,
    romantic,
    minimal,
    cinematic,
    organicTime: !baroque && !jazz && !impressionist && !classical && !romantic && !minimal && !cinematic,
    antiEtude: !baroque && !jazz && !impressionist && !classical && !romantic && !minimal && !cinematic
  };
}

/**
 * Get the behavioral overlay string for the current mode.
 * Used by plan, compose, and refine prompts.
 */
function getBehavioralOverlay(params) {
  const modeFlags = getModeFlags(params);
  if (modeFlags.baroque) return BAROQUE_COMPOSE_INSTRUCTIONS;
  if (modeFlags.jazz) return JAZZ_COMPOSE_INSTRUCTIONS;
  if (modeFlags.impressionist) return IMPRESSIONIST_COMPOSE_INSTRUCTIONS;
  if (modeFlags.classical) return CLASSICAL_COMPOSE_INSTRUCTIONS;
  if (modeFlags.romantic) return ROMANTIC_COMPOSE_INSTRUCTIONS;
  if (modeFlags.minimal) return MINIMAL_COMPOSE_INSTRUCTIONS;
  if (modeFlags.cinematic) return CINEMATIC_COMPOSE_INSTRUCTIONS;
  return DEFAULT_COMPOSE_INSTRUCTIONS;
}

/**
 * Get the plan-phase behavioral overlay (condensed version).
 */
function getPlanBehavioralOverlay(params) {
  const modeFlags = getModeFlags(params);
  if (modeFlags.baroque) return BAROQUE_PLAN_INSTRUCTIONS;
  if (modeFlags.jazz) return JAZZ_PLAN_INSTRUCTIONS;
  if (modeFlags.impressionist) return IMPRESSIONIST_PLAN_INSTRUCTIONS;
  if (modeFlags.classical) return CLASSICAL_PLAN_INSTRUCTIONS;
  if (modeFlags.romantic) return ROMANTIC_PLAN_INSTRUCTIONS;
  if (modeFlags.minimal) return MINIMAL_PLAN_INSTRUCTIONS;
  if (modeFlags.cinematic) return CINEMATIC_PLAN_INSTRUCTIONS;
  return DEFAULT_PLAN_INSTRUCTIONS;
}

/**
 * Build the full compose/refine system prompt (behavioral overlay + LilyPond template + syntax rules).
 * Single source of truth — used by initial generation AND refine pass.
 */
function getComposeSystemPrompt(params) {
  const modeFlags = getModeFlags(params);
  const overlay = getBehavioralOverlay(params);
  const bars = params.bars || 16;

  const tempoComment = modeFlags.baroque
    ? '% use expressive indications sparingly: con moto, senza rigidità, quasi improvisando'
    : modeFlags.jazz
      ? '% use a steady swing or groove tempo: Swing, With groove, Funky, etc. — NO rubato, NO fermatas'
      : modeFlags.impressionist
        ? '% use floating atmospheric markings: "Très doux", "Flottant", "Senza misura", "Sospeso", "Doucement" — NO metronomic markings'
        : modeFlags.classical
          ? '% use a clear moderate tempo: Andante, Allegretto, Moderato, Con moto — NO rubato, NO fermatas except final cadence'
          : modeFlags.romantic
            ? '% use expressive cantabile markings: rubato, con espressione, cantabile, con moto — time breathes with the melody'
            : modeFlags.minimal
              ? '% use a clear steady tempo: Andante, Moderato, or numeric (e.g., quarter=80) — NO rubato, NO fermatas'
              : modeFlags.cinematic
                ? '% use a steady moderate tempo: Andante, Moderato, or numeric (e.g., quarter=76) — NO rubato, builds through texture not tempo'
                : '% use expressive tempo markings (rubato, poco allargando, etc.)';

  return `You are an expert LilyPond engraver and composer. You have received a composer's impressionistic brief — NOT a detailed plan.
Your job is to compose and engrave a finished piano prelude that embodies the brief's tendencies and emotional stance.

${overlay}

REQUIRED LILYPOND STRUCTURE:

\\version "2.24.0"

rightHand = {
  \\clef treble
  \\key [key] \\[mode]
  \\time 4/4
  ${tempoComment}
  % ... music ...
  \\barNumberCheck #${bars + 1}
}

leftHand = {
  \\clef bass
  \\key [key] \\[mode]
  \\time 4/4
  % left hand music — add \\sustainOn/\\sustainOff pedal on notes (e.g. c4\\sustainOn e g e\\sustainOff)
  % ... music ...
  \\barNumberCheck #${bars + 1}
}

\\score {
  <<
    \\new PianoStaff <<
      \\new Staff = "RH" \\with {
        midiInstrument = "acoustic grand"
        midiMinimumVolume = #0.3
        midiMaximumVolume = #0.9
      } {
        \\rightHand
      }

      \\new Staff = "LH" \\with {
        midiInstrument = "acoustic grand"
        midiMinimumVolume = #0.2
        midiMaximumVolume = #0.7
      } {
        \\leftHand
      }
    >>
  >>
  \\layout { }
  \\midi {
    \\tempo 4 = ${
      modeFlags.jazz ? 116
      : modeFlags.classical ? 104
      : modeFlags.minimal ? 80
      : modeFlags.cinematic ? 80
      : modeFlags.impressionist ? 66
      : 76
    }
  }
}

BAR COUNT ENFORCEMENT:
- The piece MUST have exactly ${bars} full bars in each hand
- Place \\barNumberCheck #${bars + 1} as the LAST item before the closing brace in BOTH rightHand and leftHand
- If LilyPond warns about a bar number mismatch, fix the measure count — do NOT remove \\barNumberCheck

SUSTAIN PEDAL (mandatory for natural piano sound):
- Add sustain pedal to the LEFT HAND only — attach \\sustainOn and \\sustainOff directly to notes.
- Syntax: place \\sustainOn immediately after a note's duration, before the next note. Example:
    c4\\sustainOn e g e\\sustainOff | f4\\sustainOn a c a\\sustainOff |
- Change pedal at each harmonic change (typically once per bar or every 2 bars).
- For impressionist/romantic styles: change pedal every 1-2 bars, sometimes half-pedal (\\sustainOff\\sustainOn quickly).
- For baroque: DO NOT add sustain pedal (harpsichord has no sustain).
- For minimal style: hold pedal for 4+ bars between changes.
- For jazz: NO sustain pedal on moving quarter-note or eighth-note bass lines — it blurs the groove. Only add \sustainOn to whole notes or explicitly held chords (half note or longer). Most jazz bars should have NO pedal at all.
- The final note or chord in the piece must have \\sustainOff on the last note before \\barNumberCheck.
- Without sustain pedal, piano MIDI will sound choppy and artificial.

REGISTER LIMITS (hard limits — violating these produces unplayable or ugly engraving):
- LEFT HAND lowest note: c,  (C2) — never write c,, or lower. Notes like g,,,, f,,,, bes,,, etc. are BELOW the piano keyboard and are FORBIDDEN.
- RIGHT HAND in treble clef lowest note: c' (middle C, C4) — do not write notes below c' in the right hand unless briefly passing; never go below f (F3).
- RIGHT HAND in bass clef (if ever used): same floor as left hand — c, (C2).
- These limits prevent excessive ledger lines and sub-piano-range notes.
- Examples of FORBIDDEN notes: c,,,  g,,,  f,,,  bes,,,  d,,  (anything with 3+ commas, or 2 commas below G)
- If a passage needs to be low, raise it by one octave rather than crossing the floor.

SYNTAX RULES:
- Articulations come AFTER duration: c'4-> (correct), c'->4 (wrong)
- Use articulations SPARINGLY (max 2-3 per phrase)
- Crescendo/decrescendo must be paired: \\< ... \\!
- Never combine articulations with dynamics: c'16->\\< is INVALID
- Dynamic contour is REQUIRED: include at least one soft marking (pp/p/mp) and one strong marking (mf/f/ff) across the piece
- Use accent language for buildup/power where musically justified: >, ^, or \\sfz (sparingly, not every bar)
- Shape power with hairpins and dynamic contrast; avoid staying at one dynamic level throughout
- Keep each hand physically playable: avoid vertical stacks wider than an octave + third unless explicitly rolled
- Avoid dense pitch clusters and repeated multi-note piles; default to single-note lines or two-note intervals
- Large leaps (> octave) should be occasional, not continuous texture
- All braces must be balanced
- Use \\fermata very sparingly: maximum 2-3 per piece total, only at significant phrase endings
- Do NOT change \\time mid-piece unless explicitly requested
- If using \\partial for pickup, BOTH hands must share the same pickup structure`;
}

/**
 * Baroque/Bach-adjacent behavioral instructions.
 * Replaces the default Core Composition Instructions when Baroque mode is active.
 */
const BAROQUE_PLAN_INSTRUCTIONS = `--- BAROQUE BEHAVIORAL PHILOSOPHY ---

Role: You are composing music that behaves like real written music, not music that demonstrates knowledge of a style.

1. Anti-Pastiche Rule (global, mandatory)
- Do not attempt to "sound like Bach"
- Do not spotlight stylistic features
- Do not explain musical ideas through clear exposition
- If the piece feels like it is referencing Bach rather than needing to exist, revise

2. Motion First, Material Second
- Do NOT clearly introduce a motif at the beginning
- Avoid intervallic cells that can be named or summarized
- Let figuration be the material
- Bach does not present ideas. He moves, and ideas emerge incidentally

3. Continuous figuration is primary
- At least one voice must maintain near-continuous motion
- Avoid block textures, static pedals, or sustained "support" roles
- Motion may thin, but it must not stop unless structurally necessary

4. Harmony as Consequence
- Harmony should feel dragged along by motion, not aimed at
- Tonic arrival should feel incidental or delayed
- If a cadence feels "earned", it is probably too obvious

5. Texture Independence
- Left hand must not act as accompaniment
- Right hand must not act as melody
- Both hands participate in motion and counter-motion

6. Emotional Stance
- Compose as if the piece was not commissioned and does not need approval
- The music should feel indifferent to the listener

7. Default Bias Overrides (AI-specific)
- Actively resist: pastiche signaling, clear exposition, polite endings, even pacing
- When in doubt: choose motion over statement, overlap over clarity

--- END PHILOSOPHY ---`;

const BAROQUE_COMPOSE_INSTRUCTIONS = `--- PRELUDE: BAROQUE BEHAVIORAL INSTRUCTIONS ---

Role: You are composing music that behaves like real written music, not music that demonstrates knowledge of a style.

1. ANTI-PASTICHE RULE (global, mandatory)
Do not attempt to "sound like Bach". Do not spotlight stylistic features.
Do not explain musical ideas through clear exposition.
If the piece feels like it is referencing Bach rather than needing to exist, revise.

2. MOTION FIRST, MATERIAL SECOND
2.1 No motif declaration
- Do not clearly introduce a motif at the beginning
- Avoid intervallic cells that can be named or summarized
- Let figuration be the material
- Bach does not present ideas. He moves, and ideas emerge incidentally.

2.2 Continuous figuration is primary
- At least one voice must maintain near-continuous motion
- Avoid block textures, static pedals, or sustained "support" roles
- Motion may thin, but it must not stop unless structurally necessary
- If the texture pauses to "say something", it is wrong

3. TIME IS HIERARCHICAL, NOT EVEN (critical)
3.1 Meter ≠ felt time
- The written meter may remain constant
- The experienced time must be unequal
- Achieve this through: overlapping voices, suspensions that lean forward, rhythmic inequality, note groupings that resist barlines
- Never treat the barline as an arrival point

3.2 Dance rhetoric without choreography
- If the piece implies a dance meter: accents must be implied not hammered, downbeats must often be softened, energy should flow through the barline
- If MIDI playback sounds square, exaggerate inequality in notation

4. AVOID PLANNED IRREGULARITY
- Do not insert "surprises" by plan
- Do not truncate phrases for effect
- Irregularity must arise from: voice-leading pressure, harmonic necessity, contrapuntal overlap
- Bach's asymmetry is a byproduct, not a feature

5. HARMONY AS CONSEQUENCE, NOT DESTINATION
- Avoid functional cadences as goals
- Harmony should feel dragged along by motion, not aimed at
- Tonic arrival should feel incidental or delayed
- If a cadence feels "earned", it is probably too obvious

6. TEXTURE INDEPENDENCE (hands are not roles)
- Left hand must not act as accompaniment
- Right hand must not act as melody
- Both hands participate in motion and counter-motion
- If one hand exists primarily to support the other, revise

7. TEMPO & TEMPORAL AUTHORITY (Bach-specific)
7.1 No metronomic authority
- Avoid numeric tempos
- Use expressive indications sparingly: con moto, senza rigidità, quasi improvisando
- Time should feel remembered, not enforced

7.2 Rhetorical stretching
- Allow written suspensions and overlaps to imply: hesitation, urgency, overrun
- Do not rely on performer rubato to fix rigid writing

8. ENDINGS: STOP, DON'T CONCLUDE
- Avoid rhetorical "finality"
- Do not slow down to announce the end
- Prefer endings that feel like: motion stopping due to exhaustion, texture thinning until nothing remains, harmonic arrival without ceremony
- If the ending says "this is the end", it is wrong

9. MIDI REALITY CHECK (internal)
- Assume MIDI playback will flatten rhetoric
- Therefore: exaggerate inequality in notation, overemphasize overlaps and suspensions, distrust even rhythms
- Write against the MIDI engine

10. INTERNAL AUTHENTICITY TEST
Before finalizing, silently ask:
- Does this feel like continuous thought?
- Could any section be labeled or summarized?
- Does the music move because it must, or because it was planned?
If it feels planned, revise.

ANCHOR: Compose as if the barline is an inconvenience, the cadence is an accident, and motion is the only truth.

--- END BAROQUE INSTRUCTIONS ---`;

const JAZZ_PLAN_INSTRUCTIONS = `--- JAZZ BEHAVIORAL PHILOSOPHY ---

Role: You are composing music that grooves, swings, and breathes with rhythmic life — not a classical prelude in disguise.

1. RHYTHM IS EVERYTHING
- The piece must feel syncopated. Melody anticipates the beat; bass lands on it.
- Avoid straight quarter-note or eighth-note melody lines. Off-beat accents are the default.
- At least one hand should imply swing or shuffle feel at all times.

2. HARMONY IS FUNCTIONAL AND RICH
- Use ii-V-I progressions as the structural backbone.
- The piece must move through at least 4 distinct chords — NOT stay diatonic to one key.
- Include at least one 7th chord, one 9th or 11th extension, and one chromatic approach chord.
- Avoid purely diatonic progressions — they sound classical, not jazz.

3. MELODY USES JAZZ VOCABULARY
- Plan for blue notes: b3, b7, or b5 relative to the home key — these are mandatory colour notes.
- Melody outlines chord tones (3rd, 5th, 7th) rather than running up/down the major scale.
- Chromatic approach notes before landing on chord tones.

4. LEFT HAND = GROOVE ENGINE
- Left hand provides rhythmic grounding: walking bass or stride.
- Walking bass: one note per beat, outlining ROOT MOVEMENT through chord changes (NOT just walking up/down one scale).
- Stride: bass note on beat 1+3, chord on beat 2+4.
- Do NOT write flowing arpeggios or scale runs in the left hand.

5. TEMPO IS STEADY
- Jazz has a pulse. Do NOT use rubato, fermatas, or tempo fluctuations.
- Use a clear swing or groove marking (e.g., "With swing", "Funky", "Bright swing").

6. AVOID CLASSICAL HABITS
- No flowing 16th-note scalar lines in the right hand
- No "senza rigidità", "quasi fermata", "tempo sospeso" markings
- No extremely low bass register (stay above C,, in the left hand)
- No imitative counterpoint

--- END JAZZ PHILOSOPHY ---`;

const JAZZ_COMPOSE_INSTRUCTIONS = `--- PRELUDE: JAZZ BEHAVIORAL INSTRUCTIONS ---

Role: You are writing a jazz-flavored piano piece that grooves and swings — not a classical prelude.

1. RHYTHM (mandatory)
- Melody must be syncopated: anticipate beats, land off the beat, use tied notes across barlines.
- Every phrase should have at least one off-beat accent or anticipation.
- Avoid straight quarter-note or eighth-note melody lines entirely.

2. LEFT HAND = WALKING BASS THROUGH CHORD CHANGES (mandatory)
- Walking bass: one note per beat, outlining the ROOT MOVEMENT of chord changes — NOT just walking up and down one scale.
- The bass must imply real chord changes. Example of a ii-V-I in G:
    a,4 b, c d | g, a, b, c | g,4 fis, g, a, (Am7 → D7 → Gmaj)
- Contrast: "e fis gis a / b a gis fis / e fis gis a" is WRONG — that is just an E major scale, not a walking bass implying chord changes.
- Each 2–4 bars should imply a different chord (e.g. Am7, D7, Gmaj7, Em7, Bm7).
- STRIDE alternative: bass note on beats 1+3, 3-note voicing on beats 2+4.
- DO NOT write broken chord arpeggios (fis4 a4 cis'4 a4 = wrong).
- Walking bass stays in the range C, to c' — no extreme low notes.

3. MELODY MUST USE JAZZ VOCABULARY (mandatory)
- Include blue notes: the flatted 3rd (b3), flatted 7th (b7), or flatted 5th (b5) of the key.
- Use chromatic approach notes: half-step above or below chord tones before landing.
- The melody should outline chord tones (3rd, 5th, 7th of each chord), NOT just run up and down the major scale.
- If the key is E major: use g natural (b3), d natural (b7), bes (b5) as colour notes.
- WRONG: a purely diatonic melody that only uses notes of the home key. That sounds classical, not jazz.

4. HARMONY — CHORD CHANGES ARE MANDATORY
- ii-V-I is your structural backbone. Use it at least twice per section.
- Include: at least two dominant 7th chords, one chord with 9th or 11th extension.
- The piece must move through at least 4 distinct chords — NOT stay on one tonic.
- Use chromatic approach notes (half-step above or below chord tones).
- One tritone substitution is encouraged.

5. TEMPO AND FEEL
- Use a steady, clear tempo marking: "With swing", "Funky", "With groove", "Bright swing", "Laid-back".
- Do NOT use: rubato, senza rigidità, quasi fermata, tempo sospeso, poco allargando, or any fermata.
- The pulse must be unwavering throughout.

6. ARTICULATION
- Use staccato (.) on off-beat notes to imply swing.
- Accents (>) on syncopated arrivals.
- Keep dynamics lively: mp to f range with clear contrast.

7. FORBIDDEN IN JAZZ MODE
- Purely diatonic melody (no blue notes = not jazz)
- Walking bass that never leaves the home key (= scale exercise, not jazz)
- Flowing scalar 16th-note lines in either hand
- Fermatas or tempo changes
- Imitative counterpoint
- Extreme low register in left hand (below C,)

ANCHOR: The piece must make you want to tap your foot AND have blue notes that give it that jazzy ache. If it sounds like Bach or a major-scale exercise, it is wrong.

--- END JAZZ INSTRUCTIONS ---`;

const IMPRESSIONIST_PLAN_INSTRUCTIONS = `--- IMPRESSIONIST BEHAVIORAL PHILOSOPHY ---

Role: You are composing in the style of Debussy or Ravel — music that floats, shimmers, and suspends time. NOT a classical prelude, NOT a baroque exercise.

1. TEXTURE IS THE PIECE
- Left hand: continuous arpeggiated broken chords, spanning 2+ octaves, moving through every bar. The LH never stops. Never rests.
- Right hand: long, singing melodic lines — quarter notes, half notes, tied notes floating above the arpeggios.
- The two hands must NEVER both rest simultaneously. If RH rests, LH must be moving.

2. HARMONY = COLOR, NOT FUNCTION
- Extended chords throughout: major 7th, add9, sus2, parallel chord motion.
- Use whole-tone passages or pentatonic color in at least one section.
- Avoid V-I resolutions as structural events. Let harmony drift rather than resolve.
- No plain triads without added color.

3. NO FRAGMENTATION
- Do NOT write fragmented 16th-note snippets in either hand.
- Do NOT write disconnected gestures with rests in between every phrase.
- Both hands must sustain continuous motion and continuity.

4. MELODY IS LONG AND SINGING
- RH melody should use legato quarter/half note lines — no rapid ornamental figuration.
- A short melodic cell should be developed through register shifts and harmonic recoloring, never literally repeated.

5. ATMOSPHERE OVER STRUCTURE
- No clear cadences, no announcement of form.
- Phrases breathe and overlap — no clean phrase endings.
- Time should feel suspended, floating, without pulse.

--- END IMPRESSIONIST PHILOSOPHY ---`;

const IMPRESSIONIST_COMPOSE_INSTRUCTIONS = `--- PRELUDE: IMPRESSIONIST BEHAVIORAL INSTRUCTIONS ---

Role: You are writing an impressionist piano piece in the style of Debussy — shimmering, floating, atmospheric. NOT a classical piece, NOT a baroque exercise.

1. LEFT HAND = CONTINUOUS ARPEGGIOS (mandatory — this is the most important rule)
- Left hand plays broken chord arpeggios spanning at least 2 octaves throughout the piece.
- The LH must NEVER stop moving. No long rests in the LH. If you write a rest in the LH, delete it.
- Use rich extended chords for the arpeggios: Gmaj7, Cadd9, Fsus2, parallel major 7th motion.
- The arpeggios create a shimmering, continuous harp-like texture beneath the melody.

2. RIGHT HAND = LONG SINGING MELODY (mandatory)
- Right hand plays a long, legato melodic line: quarter notes, half notes, tied notes.
- The melody floats above the LH arpeggios — think of the opening of Clair de Lune.
- Do NOT write fragmented 16th-note melodic snippets. No short disconnected gestures.
- No rapid ornamental figuration. Melody is slow and singing.

3. CRITICAL CONSTRAINT: BOTH HANDS NEVER REST TOGETHER
- If RH has a rest, LH must be playing arpeggios underneath.
- If LH has a rest (maximum 1 bar), RH must have a sustained melody note.
- The texture must feel continuous and unbroken.

4. HARMONY = IMPRESSIONIST COLOR
- Use extended chords throughout: major 7th, add9, sus2, 6th chords.
- Include at least one passage of whole-tone or pentatonic color.
- Use parallel chord motion (parallel major 7ths, parallel 9ths).
- Avoid plain triads. Avoid V-I cadences as structural points.

5. TEMPO AND ATMOSPHERE
- Use floating tempo markings: "Très doux", "Flottant", "Senza misura", "Sospeso", "Doucement".
- No steady pulse or metronomic feel.
- Time should feel suspended and atmospheric.

6. FORBIDDEN IN IMPRESSIONIST MODE
- Fragmented 16th-note melodic snippets in the RH
- Both hands resting simultaneously
- Staccato, sharp accents, dry textures
- Walking bass or stride patterns in the LH
- Functional V-I harmony as structural anchors
- Scalar runs without harmonic color
- Plain triads (add a 7th, 9th, or suspension to every chord)

ANCHOR: The piece should feel like light on water — the LH is the water (always moving), the RH is the light (floating above). If it sounds dry, fragmented, or classical, it is wrong.

--- END IMPRESSIONIST INSTRUCTIONS ---`;

const CLASSICAL_PLAN_INSTRUCTIONS = `--- CLASSICAL BEHAVIORAL PHILOSOPHY ---

Role: You are composing in the style of Mozart or Haydn — music of wit, balance, and periodic grace. NOT a romantic outpouring, NOT an impressionist blur.

1. PHRASING IS PERIODIC
- Structure in clear 4+4 bar phrases. Phrase endings must be audible.
- Plan one disruption: a truncated phrase, an extra bar, or an overlapping entry — no more.
- Symmetry is a virtue here, not an enemy.

2. TEXTURE IS STRATIFIED
- Right hand carries the melody. Left hand provides harmonic support.
- LH choices: Alberti bass (broken chord triplet), quarter-note harmonic rhythm (2 beats per chord), or simple repeated chords.
- The two hands have clear, non-competing roles.

3. HARMONY IS TRANSPARENT
- Use I-IV-V-I cadential plans. State the harmonic rhythm clearly.
- One applied dominant (V/V or V/IV) is allowed. No more.
- Avoid chromatic passing tones. Avoid deceptive cadences as structural points.

4. TEMPO IS MODERATE AND STEADY
- Choose a clear character tempo: Andante, Allegretto, Moderato.
- No rubato, no fermatas except at the final cadence.
- The pulse is the piece.

5. AVOID
- Constant running 16th-note figuration in both hands
- Chromatic voice-leading
- Dense, heavy textures
- Romantic or impressionist expressive markings

--- END CLASSICAL PHILOSOPHY ---`;

const CLASSICAL_COMPOSE_INSTRUCTIONS = `--- PRELUDE: CLASSICAL BEHAVIORAL INSTRUCTIONS ---

Role: You are writing a classical piano piece in the style of Mozart or early Haydn — clear, witty, balanced, and graceful. NOT romantic, NOT impressionist.

1. PHRASING (mandatory)
- Write in clear 4+4 bar phrases. Every phrase should have an audible beginning and ending.
- Plan one disruption across the whole piece: a truncated phrase (3 bars instead of 4), an extra bar inserted, or overlapping entries.
- DO NOT disrupt every phrase. Regularity is a feature.

2. TEXTURE (mandatory)
- Right hand: melody — singing, stepwise, with occasional leaps of a 3rd or 6th.
- Left hand: harmonic support. Choose one of:
  a) Alberti bass: low note, mid chord, high chord repeated (um-pah-pah feel)
  b) Two-beat harmonic rhythm: root on beat 1, chord on beat 3
  c) Simple quarter-note chord pulses
- The LH must NOT have independent melodic lines. It supports.

3. HARMONY
- Plan a clear I-IV-V-I cadence structure. Cadences at phrase endings.
- One applied dominant allowed (e.g., V/V before the dominant arrival).
- Avoid chromatic passing tones. Avoid augmented 6th chords.
- Tonic-dominant polarity drives the piece.

4. TEMPO AND CHARACTER
- Use a clear, moderate tempo marking: Andante, Allegretto, Moderato, Con moto.
- The tempo must remain steady throughout.
- NO rubato, NO senza rigidità, NO fermatas except at the final cadence.
- Dynamic markings: p and f contrasts at phrase endings (echo dynamics).

5. ARTICULATION AND DYNAMICS
- Use slurs over melodic phrases (2-4 bar spans).
- Staccato on repeated notes and cadential figures.
- Echo dynamic contrasts: f answered by p on repeats.

6. FORBIDDEN IN CLASSICAL MODE
- Rubato, senza rigidità, or any tempo flexibility markings
- Continuous 16th-note figuration in both hands simultaneously
- Chromatic voice-leading or romantic harmony
- Independent melodic material in the LH
- Dense or heavy textures
- Fermatas except at the very final cadence

ANCHOR: The piece should feel like a well-reasoned argument — each phrase completes a thought. If it sounds like Chopin or Debussy, it is wrong.

--- END CLASSICAL INSTRUCTIONS ---`;

const ROMANTIC_PLAN_INSTRUCTIONS = `--- ROMANTIC BEHAVIORAL PHILOSOPHY ---

Role: You are composing in the style of Chopin — music of lyrical expression, delayed resolution, and singing melody. NOT classical balance, NOT impressionist color.

1. MELODY IS THE SOUL
- Right hand carries a long, arching, cantabile melody.
- The melody should rise, peak, and descend across each phrase.
- Melody should resist its cadence — delay, extend, ache before resolving.

2. LEFT HAND IS ACCOMPANIMENT
- LH provides a flowing broken-chord or arpeggiated accompaniment.
- Wide-spanning LH gestures (reaching a 10th or more) create the characteristic "Chopin wash."
- LH moves continuously but never competes with the RH melody.

3. HARMONY IS EXPRESSIVE
- Use one deceptive cadence (V-vi instead of V-I) as a structural surprise.
- Chromatic approach to the dominant (chromatically raised 4th scale degree, etc.)
- Harmony is functional but inflected — not impressionist drift.

4. RUBATO IS STRUCTURAL
- Time should breathe with the melody — not mechanical.
- Phrase endings stretch; phrase beginnings hesitate.
- Rubato serves emotional expression, not temporal ambiguity.

5. AVOID
- Stiff, metronomic phrasing
- Alberti bass or simple harmonic rhythm in LH (too classical)
- Surface chromaticism without expressive purpose
- Even phrase lengths throughout

--- END ROMANTIC PHILOSOPHY ---`;

const ROMANTIC_COMPOSE_INSTRUCTIONS = `--- PRELUDE: ROMANTIC BEHAVIORAL INSTRUCTIONS ---

Role: You are writing a romantic piano piece in the style of Chopin — lyrical, expressive, with a singing RH melody over LH arpeggiated accompaniment. NOT classical, NOT impressionist.

1. RIGHT HAND = SINGING MELODY (mandatory)
- RH carries a long, legato, cantabile melodic line.
- Use quarter notes, dotted rhythms, and tied notes to create a singing arc.
- The melody should have a clear rise (tension) and fall (release) over each phrase.
- Avoid scalar runs as primary melody. The melody should feel vocal, not pianistic.

2. LEFT HAND = ARPEGGIATED ACCOMPANIMENT (mandatory)
- LH plays broken chord accompaniment patterns — NOT Alberti bass, NOT a walking bass.
- Wide-spanning gestures reaching an octave or more (bass note + spread chord above).
- Pattern: bass note on beat 1, then broken chord rising through the bar.
- LH moves continuously but always subordinate to the RH melody.
- The LH may briefly rest at a melodic peak to let the melody speak alone.

3. PHRASE SHAPE (mandatory)
- Each 4-bar phrase should have a melodic arc: ascent then descent.
- Extend one phrase by 2 bars via a melodic sequence.
- Use silence (half-bar rest in LH at melodic peak) to intensify the melody.

4. HARMONY
- Functional I-IV-V-I backbone with expressive color.
- Include one deceptive cadence (V to vi) as a structural surprise.
- Use chromatic approach notes to the dominant (raised 4th scale degree).
- Avoid plain diatonic harmony throughout — at least one chromatic inflection per phrase.

5. TEMPO AND RUBATO
- Use expressive tempo markings: rubato, con espressione, cantabile, con moto.
- Time should breathe with the melody: phrase endings stretch, beginnings hesitate.
- The piece must feel emotionally alive, not metronomic.

6. DYNAMICS
- Shape dynamics with the melody: crescendo to the phrase peak, decrescendo away.
- Use pp and p for introspective passages, mf-f at climax.
- The ending should fade — pp or ppp, not a strong cadential statement.

7. FORBIDDEN IN ROMANTIC MODE
- Alberti bass or simple repeated chords in LH
- Stiff, metronomic phrasing
- Steady unwavering pulse throughout (the time must breathe)
- Both hands running simultaneously in 16th-note figuration
- Ending with a forte cadence (Chopin nocturnes end softly)
- LH competing with RH for melodic attention

ANCHOR: Close your eyes and sing the right hand. If it sings, the piece is working. The LH should feel like a cushion of sound beneath the singing line. If it sounds classical or impressionist, it is wrong.

--- END ROMANTIC INSTRUCTIONS ---`;

const MINIMAL_PLAN_INSTRUCTIONS = `--- MINIMAL/AMBIENT BEHAVIORAL PHILOSOPHY ---

Role: You are composing in the style of Philip Glass or ambient minimalism — music of hypnotic repetition, gradual change, and stillness. NOT jazz, NOT classical.

1. ONE HAND = OSTINATO ENGINE
- One hand (usually LH) maintains a repeating rhythmic-melodic cell throughout.
- The cell uses 3-5 pitches. It repeats with minimal variation.
- The ostinato IS the piece — it should feel hypnotic, not busy.

2. OTHER HAND = SLOW MELODY
- The other hand (usually RH) adds sparse, slow melodic notes above.
- At least one new pitch every 4 bars.
- Long tones, not scalar lines or ornamental figures.

3. HARMONY CHANGES SLOWLY
- One chord change every 6-8 bars minimum. No rapid harmonic rhythm.
- No sudden modulations. Harmony should drift, not pivot.
- Avoid functional I-IV-V-I. Modal or drone-like harmonic language.

4. PULSE IS UNWAVERING
- Minimal music has a clear, steady pulse — like a clock.
- No rubato, no fermatas, no tempo changes (except a final slowing at the very end).
- The pulse is what makes the gradual change audible.

5. AVOID
- Dramatic climax or sudden forte
- Dense, busy textures
- Rapid harmonic rhythm
- Scalar runs or melodic development

--- END MINIMAL PHILOSOPHY ---`;

const MINIMAL_COMPOSE_INSTRUCTIONS = `--- PRELUDE: MINIMAL/AMBIENT BEHAVIORAL INSTRUCTIONS ---

Role: You are writing a minimalist piano piece in the style of Philip Glass — hypnotic, repetitive, gradually shifting. NOT jazz, NOT classical, NOT impressionist.

1. LEFT HAND = REPEATING OSTINATO (mandatory)
- LH plays a repeating rhythmic-melodic cell using 3-5 distinct pitches.
- The pattern repeats EVERY bar (or every 2 bars) throughout the piece.
- Variation should be minimal: slight register shift, one pitch swapped — not a new pattern.
- The LH ostinato must never stop for more than 1 bar.

2. RIGHT HAND = SPARSE SLOW MELODY (mandatory)
- RH adds slow, widely-spaced melodic notes above the LH ostinato.
- Long note values: half notes, dotted half notes, whole notes.
- At least one new RH pitch every 4 bars. No rapid melodic figuration.
- The RH melody drifts slowly — it does NOT develop, vary rhythmically, or ornament.

3. TOGETHER: 5+ PITCH CLASSES (mandatory)
- Both hands combined must use at least 5 distinct pitch classes.
- Do not restrict the whole piece to 2-3 pitches.

4. HARMONY CHANGES SLOWLY
- Change the underlying harmony (implied by LH pitches) no more than once every 6-8 bars.
- No sudden modulations. No functional cadences.
- Let the harmony shift almost imperceptibly — the listener should notice it has changed, not when.

5. PULSE IS STEADY AND UNWAVERING
- Use a clear, moderate tempo: Andante, Moderato, or a numeric tempo like ♩= 80.
- NO rubato, NO fermatas, NO tempo changes mid-piece.
- The steady pulse makes the gradual drift audible. Without it, minimal music collapses.

6. ARC: GRADUAL AND SUBTLE
- No dramatic climax. No sudden forte or texture explosion.
- The piece may gradually thicken (add one voice, shift register upward) and then thin again.
- The ending may slow very slightly (poco ritardando) but should not announce itself.

7. FORBIDDEN IN MINIMAL MODE
- Dramatic dynamic surges (sudden ff or fff)
- Rapid harmonic rhythm (chord changes every 1-2 bars)
- Scalar runs or melodic development in either hand
- Rubato, senza rigidità, or expressive tempo markings
- Both hands playing completely different, unrelated material
- Fermatas before the final note

ANCHOR: The piece should feel like watching a slow tide — the water moves, but the change is almost imperceptible. If it sounds like jazz or classical, it is wrong.

--- END MINIMAL INSTRUCTIONS ---`;

const CINEMATIC_PLAN_INSTRUCTIONS = `--- CINEMATIC BEHAVIORAL PHILOSOPHY ---

Role: You are composing in the style of Hans Zimmer — modern cinematic piano music with a clear emotional arc from sparse to full. NOT classical, NOT impressionist.

1. THE PIECE IS AN ARC
- Begin sparse: single notes, wide spacing, space between events.
- Build gradually: add texture, double notes, widen register.
- Climax: full octave doubling, both hands engaged, peak dynamic.
- Return to sparse or end on a single sustained note.
- The arc is the piece. Every bar should know where it is in the journey.

2. TEXTURE IS ARCHITECTURE
- Opening: single notes or 2-note intervals in RH, minimal LH.
- Middle: simple broken chord patterns in LH, fuller RH melody.
- Climax: RH octave doubling, both hands in octave unison or thick chords.

3. HARMONY IS MODAL
- Use Aeolian, Dorian, or Mixolydian modes — not classical major/minor.
- bVII and bVI chords as color. Avoid the leading tone.
- Authentic cadence (V-I or v-i) only at the very end.

4. PULSE IS STEADY AND BUILDING
- Steady pulse throughout. The momentum builds through texture, not tempo.
- No rubato, no expressive tempo markings. The piece drives forward.

5. AVOID
- Classical periodic phrasing (4+4 bars with cadences)
- Functional harmony (ii-V-I)
- Imitative counterpoint
- Impressionist texture (continuous LH arpeggios)

--- END CINEMATIC PHILOSOPHY ---`;

const CINEMATIC_COMPOSE_INSTRUCTIONS = `--- PRELUDE: CINEMATIC BEHAVIORAL INSTRUCTIONS ---

Role: You are writing a modern cinematic piano piece in the style of Hans Zimmer — building from sparse to full, with a single emotional trajectory. NOT classical, NOT jazz, NOT impressionist.

1. STRUCTURE = ARC (mandatory)
The piece must follow this trajectory:
- Bars 1-4: SPARSE — single notes or 2-note intervals in RH. LH minimal (long held notes or nothing).
- Bars 5-12: BUILDING — LH begins simple repeated pattern (quarter-note pulse or 2-note ostinato). RH develops a melodic line.
- Bars 13-18: CLIMAX — RH in octaves. LH full chords or octave bass. Both hands at peak register and dynamic.
- Bars 19-end: RETURN — texture thins back to sparse. End on a single note, octave, or sustained chord, ppp.

2. TEXTURE BUILDS THROUGH DOUBLING (mandatory)
- Sparse opening: RH single notes. LH one note per bar or silent.
- Building: RH simple melody. LH adds quarter-note pulse (same pitch class as harmony).
- Climax: RH doubles at the octave. LH full, strong bass + chord or octave.
- The increase in density should feel inevitable, not sudden.

3. HARMONY IS MODAL
- Choose a mode: Aeolian (natural minor), Dorian, or Mixolydian.
- Use bVII and bVI chords as your primary color chords.
- Avoid the leading tone (raised 7th). Avoid dominant 7th chords before the final cadence.
- The final cadence (last 2 bars) is the ONE moment of harmonic arrival: V to I (or v to i).

4. MELODY IS INTERVALLIC
- The main melodic motif uses a perfect 4th or perfect 5th as its opening interval.
- The melody repeats and gradually rises in register as the piece builds.
- No ornamental figuration, no scalar runs as primary material.

5. TEMPO AND DYNAMICS
- Use a steady, moderate tempo: Andante, Moderato, or ♩= 72-88.
- NO rubato, NO expressive tempo markings. The piece moves forward steadily.
- Dynamic arc: pp (sparse) → mp (building) → f/ff (climax) → pp (return).
- Mark dynamics explicitly at each section change.

6. FORBIDDEN IN CINEMATIC MODE
- Classical periodic phrasing or cadences before the final bar
- Functional ii-V-I harmony (too jazz/classical)
- Impressionist LH arpeggios throughout (wrong texture)
- Rubato or senza rigidità tempo markings
- Staccato or dry articulation
- Remaining at one dynamic level throughout

ANCHOR: The piece tells one story — departure and arrival. If someone cannot sense the arc from quiet to full to quiet again, something is wrong. If it sounds like Mozart or Chopin, it is wrong.

--- END CINEMATIC INSTRUCTIONS ---`;

const DEFAULT_PLAN_INSTRUCTIONS = `--- CORE COMPOSITION PHILOSOPHY ---

Role: You are composing a finished musical work, not an exercise, étude, demonstration, or example.
Your goal is to create a piece that feels internally motivated, temporally elastic, and emotionally lived-in.

1. Anti-Exercise Rule (global)
Do not conceive music that clearly demonstrates a technique, announces its structure, or teaches a concept.
If a passage could be labeled ("this is the motif", "this is the sequence"), rethink it.
Music should feel discovered, not explained.

2. Temporal Awareness
- The piece should not feel governed by a single fixed tempo
- At least two sections should feel hesitant, suspended, or temporally unclear
- Phrase endings should stretch, blur, or overlap — not resolve cleanly in time

3. Material Rules
- Do not plan a clearly stated motif at the beginning
- If material recurs, it must be incomplete, obscured, or altered beyond recognition
- Avoid explicit "development" — let ideas decay, not complete

4. Form Rules
- Do not pre-label sections internally
- Avoid tidy proportions — permit asymmetry, extra bars, missing bars
- At least one formal idea must fail to resolve
- The ending does not need to feel justified

5. Left Hand / Texture Autonomy
- Left hand must not behave as a static support system
- LH may drift independently, contradict RH rhythm, introduce motion that never stabilizes

6. Emotional Stance
Compose as if the piece was not commissioned, does not need approval, and may never be heard again.
The music should feel indifferent to the listener, not accommodating.

7. Default Bias Overrides (AI-specific)
Actively resist: symmetry, balance, clear exposition, polite endings, even pacing.
When in doubt: choose ambiguity over clarity, drift over direction, texture over silence.
Both hands must maintain presence throughout — silence in both hands simultaneously is not ambiguity, it is absence.

--- END PHILOSOPHY ---`;

const DEFAULT_COMPOSE_INSTRUCTIONS = `--- PRELUDE: CORE COMPOSITION INSTRUCTIONS ---

Role: You are composing a finished musical work, not an exercise, étude, demonstration, or example.
Your goal is to create a piece that feels internally motivated, temporally elastic, and emotionally lived-in.

1. ANTI-EXERCISE RULE (global)
Do not write music that: clearly demonstrates a technique, announces its structure, or teaches a concept.
If a passage sounds like it could be labeled ("this is the motif", "this is the sequence"), revise it.
Music should feel discovered, not explained.

2. TEMPORAL BEHAVIOR RULES (critical)
2.1 Tempo is expressive, not numeric
- Avoid a single fixed tempo governing the entire piece
- Prefer expressive tempo markings: rubato, senza rigidità, poco allargando, quasi fermata, tempo sospeso
- Use numeric tempo only if absolutely necessary, and treat it as approximate

2.2 Time must misbehave
- At least two sections per piece must feel hesitant, suspended, or temporally unclear
- Perceived tempo should change via note density, ties across barlines, rhythmic compression or thinning — not via mechanical acceleration
- If a section could be played comfortably to a click track, it is too rigid

2.3 Phrase breathing is mandatory
- Phrase endings should often stretch, blur, or overlap
- Written ritardando/allargando should cross barlines and avoid symmetrical placement
- Do not resolve every phrase cleanly in time

2.4 Fermatas are hesitation, not punctuation
- Maximum 3 fermatas in the entire piece
- Use fermatas on sustained tones or phrase-ending rests only — not mid-bar rests
- Fermatas should feel like thought pausing, not arrival
- Do NOT scatter fermatas across the piece as punctuation marks

3. FLOW & CONTINUITY RULES
3.1 Avoid grid-based pacing
- Do not distribute events evenly across measures
- Avoid predictable attack patterns
- Allow gestures to trail off, restart mid-thought, or overlap with the next idea

3.2 Density over pulse
- Shape time through texture thickening and thinning
- A section may feel "faster" without the tempo changing

3.3 MINIMUM TEXTURE ENGAGEMENT (mandatory — prevents "start-and-stop" output)
- At least one hand must be active (playing notes, not resting) at almost all times.
- Both hands must NOT both rest simultaneously for more than 2 consecutive beats.
- When the RH rests for a full bar, the LH must be moving beneath it.
- When the LH rests, the RH must sustain or move.
- A piece where both hands are frequently silent at the same time is WRONG.
- The LH must provide some form of harmonic presence across the whole piece — not just scattered fragments.

3.4 PHRASE FLOW (prevents stuttering/fragmented output)
- Do NOT begin the majority of phrases with a rest. Rests at the start of phrases are fine occasionally, but if every bar starts with a rest (r4, r8, r2), the music will sound "start-and-stop" and incoherent.
- At most 1 in 3 bars should begin with a rest in the right hand.
- Tempo change markings should be used sparingly: maximum 3 tempo indications in the whole piece.

4. MOTIF & MATERIAL RULES
- Do not clearly present a motif at the beginning
- If material recurs, it must be incomplete, obscured, or altered beyond recognition
- Avoid explicit "development" — let ideas decay, not complete
- If the listener can summarize the piece's material easily, it is too explicit

5. FORM RULES
- Do not pre-label sections internally
- Avoid tidy proportions — permit asymmetry, extra bars, missing bars
- At least one formal idea must fail to resolve
- The ending does not need to feel justified

6. LEFT HAND / TEXTURE AUTONOMY
- Left hand must not behave as a static support system
- Avoid long stretches of pedal tones or unchanging open intervals
- LH may drift independently, contradict RH rhythm, introduce motion that never stabilizes

7. EMOTIONAL STANCE (very important)
Compose as if: the piece was not commissioned, does not need approval, and may never be heard again.
The music should feel indifferent to the listener, not accommodating.

8. DEFAULT BIAS OVERRIDES (AI-specific)
Actively resist: symmetry, balance, clear exposition, polite endings, even pacing.
When in doubt: choose ambiguity over clarity, drift over direction, silence over explanation.

9. SUCCESS TEST (internal — check silently before finalizing)
- Does the music feel like it needed to be written?
- Does time feel elastic rather than counted?
- Does anything sound like it's proving competence? If yes, revise.

10. ANCHOR
You are not demonstrating music. You are letting music happen and stopping before it explains itself.

--- END CORE INSTRUCTIONS ---`;

/**
 * Deterministic post-check: detect static LH patterns and harmonic stasis.
 * Returns an array of issue descriptions, or empty array if clean.
 */
function checkStaticPatterns(lilypondCode) {
  const issues = [];

  const noComments = lilypondCode.replace(/%[^\n]*/g, '');

  function normalizeHand(content) {
    return content
      .replace(/%[^\n]*/g, '')
      .replace(/\\(clef|key|time|tempo|bar|barNumberCheck)[^\n]*/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function extractPitchClasses(content) {
    const notes = content.match(/\b[a-g](?:is|es|isis|eses)?/g) || [];
    return new Set(notes);
  }

  // ── Left hand checks ──
  const lhMatch = noComments.match(/leftHand\s*=\s*\{([\s\S]*?)\n\}/);
  if (lhMatch) {
    const lhNorm = normalizeHand(lhMatch[1]);
    const lhBars = lhNorm.split('|').map(b => b.trim()).filter(b => b.length > 0);

    if (lhBars.length >= 3) {
      // 3+ consecutive identical bars
      let consecutiveIdentical = 1;
      for (let i = 1; i < lhBars.length; i++) {
        if (lhBars[i] === lhBars[i - 1]) {
          consecutiveIdentical++;
          if (consecutiveIdentical >= 3) {
            issues.push(`Static left hand: bars ${i - 1}-${i + 1} are identical ("${lhBars[i].substring(0, 40)}...")`);
            break;
          }
        } else {
          consecutiveIdentical = 1;
        }
      }

      // Same pitch classes across 4+ consecutive bars
      const lhBarPitches = lhBars.map(bar => {
        const pitches = bar.match(/[a-g](?:is|es|isis|eses)?/g);
        return pitches ? [...new Set(pitches)].sort().join(',') : '';
      });
      let consecutiveSame = 1;
      for (let i = 1; i < lhBarPitches.length; i++) {
        if (lhBarPitches[i] && lhBarPitches[i] === lhBarPitches[i - 1]) {
          consecutiveSame++;
          if (consecutiveSame >= 4) {
            issues.push(`Harmonic stasis: left hand uses identical pitch classes for ${consecutiveSame} consecutive bars around bar ${i + 1}`);
            break;
          }
        } else {
          consecutiveSame = 1;
        }
      }
    }
  }

  // ── Right hand checks ──
  const rhMatch = noComments.match(/rightHand\s*=\s*\{([\s\S]*?)\n\}/);
  if (rhMatch) {
    const rhNorm = normalizeHand(rhMatch[1]);
    const rhBars = rhNorm.split('|').map(b => b.trim()).filter(b => b.length > 0);

    if (rhBars.length >= 3) {
      // 3+ consecutive identical bars in RH
      let consecutiveIdentical = 1;
      for (let i = 1; i < rhBars.length; i++) {
        if (rhBars[i] === rhBars[i - 1]) {
          consecutiveIdentical++;
          if (consecutiveIdentical >= 3) {
            issues.push(`Static right hand: bars ${i - 1}-${i + 1} are identical ("${rhBars[i].substring(0, 40)}...")`);
            break;
          }
        } else {
          consecutiveIdentical = 1;
        }
      }
    }

    // ── Global pitch variety check (both hands combined) ──
    const allPitches = extractPitchClasses(rhMatch[1] + (lhMatch ? lhMatch[1] : ''));
    const noteCount = (noComments.match(/\b[a-g](?:is|es|isis|eses)?[\d,']/g) || []).length;
    if (noteCount > 40 && allPitches.size < 4) {
      issues.push(
        `Extremely low pitch variety: only ${allPitches.size} distinct pitch class(es) used across the whole piece ` +
        `(${[...allPitches].join(', ')}). Add more harmonic color — at least 5-6 distinct pitches are needed.`
      );
    }

    // ── Simultaneous-rest (sparse texture) check ──
    if (lhMatch) {
      const lhNorm = normalizeHand(lhMatch[1]);
      const rhNorm = normalizeHand(rhMatch[1]);
      const lhBars = lhNorm.split('|').map(b => b.trim()).filter(b => b.length > 0);
      const rhBars = rhNorm.split('|').map(b => b.trim()).filter(b => b.length > 0);
      const minBars = Math.min(lhBars.length, rhBars.length);

      // A bar is "rest-heavy" if it contains no pitched notes or only a lone 8th note
      function isRestHeavy(bar) {
        const notes = (bar.match(/\b[a-g](?:is|es|isis|eses)?[\d,'"]/g) || []).length;
        return notes === 0 || (notes <= 1 && /r2\b|r1\b/.test(bar));
      }

      let simultaneousRestBars = 0;
      for (let i = 0; i < minBars; i++) {
        if (isRestHeavy(lhBars[i]) && isRestHeavy(rhBars[i])) {
          simultaneousRestBars++;
        }
      }

      const ratio = simultaneousRestBars / minBars;
      if (minBars >= 8 && ratio >= 0.30) {
        issues.push(
          `Sparse texture: both hands are simultaneously near-silent in ${simultaneousRestBars} of ${minBars} bars (${Math.round(ratio * 100)}%). ` +
          `When RH rests, LH must provide harmonic motion — and vice versa. Rewrite so at least one hand is always active.`
        );
      }
    }
  }

  // ── Fermata overuse check ──
  const fermataCount = (noComments.match(/\\fermata/g) || []).length;
  if (fermataCount > 4) {
    issues.push(
      `Fermata overuse: ${fermataCount} fermatas found. Maximum 3 per piece. ` +
      `Remove fermatas from mid-phrase rests — keep only 1-2 significant pauses.`
    );
  }

  // ── Tempo change overuse check ──
  const tempoCount = (noComments.match(/\\tempo\s+"/g) || []).length;
  // One \tempo is expected for the opening; anything beyond that is mid-piece changes
  const midPieceTempos = Math.max(0, tempoCount - 1);
  if (midPieceTempos > 3) {
    issues.push(
      `Tempo change overuse: ${midPieceTempos} mid-piece tempo changes found. Maximum 3 per piece. ` +
      `Constant tempo shifts (rubato → poco allargando → tempo sospeso every few bars) fragment the music. ` +
      `Consolidate to 1-2 expressive markings near phrase endings only.`
    );
  }

  // ── Sub-floor register check (notes below piano range or below ledger-line threshold) ──
  // LH floor: c, (C2) — anything with 3+ commas is below the piano keyboard
  // RH floor: f (F3) — anything below c' (middle C) in treble clef is excessive ledger lines
  const subFloorLH = (noComments.match(/[a-g](?:is|es|isis|eses)?,,,[,'"]*/g) || []);
  if (subFloorLH.length > 0) {
    issues.push(
      `Register too low: left hand has ${subFloorLH.length} note(s) below C2 (e.g. ${subFloorLH.slice(0,3).join(', ')}). ` +
      `These are below or at the limit of the piano keyboard and produce excessive ledger lines. ` +
      `Raise all left-hand notes with 3+ commas up by one octave.`
    );
  }
  // RH notes below F3 (f without any apostrophe, or with commas) in treble clef
  const subFloorRH = rhMatch
    ? (noComments.match(/\b[a-g](?:is|es|isis|eses)?(?:,+)[^']/g) || [])
    : [];
  if (subFloorRH.length > 2) {
    issues.push(
      `Right hand too low: ${subFloorRH.length} note(s) below C3 in treble clef (e.g. ${subFloorRH.slice(0,3).join(', ')}). ` +
      `Notes below middle C (c') in treble clef create many ledger lines. Raise these passages by an octave.`
    );
  }

  // ── RH phrase-starts-with-rest check (fragmented phrasing) ──
  if (rhMatch) {
    const rhNorm2 = normalizeHand(rhMatch[1]);
    const rhBars2 = rhNorm2.split('|').map(b => b.trim()).filter(b => b.length > 0);
    if (rhBars2.length >= 8) {
      const restStartCount = rhBars2.filter(bar => /^r[1248]\b/.test(bar)).length;
      const ratio = restStartCount / rhBars2.length;
      if (ratio >= 0.50) {
        issues.push(
          `Fragmented phrasing: ${restStartCount} of ${rhBars2.length} right-hand bars begin with a rest (${Math.round(ratio * 100)}%). ` +
          `This creates a "start-and-stop" effect. At most 1 in 3 bars should start with a rest. ` +
          `Begin phrases on pitched notes and use rests mid-phrase or at phrase ends instead.`
        );
      }
    }
  }

  return issues;
}

/**
 * Throw if compileLilyPond returned barcheck warnings.
 * Barcheck failures exit with code 0 but produce misaligned MIDI — treat as errors.
 */
function assertNoBarcheckFailures(outputs) {
  const warnings = outputs.barcheckWarnings;
  if (!warnings || warnings.length === 0) return;

  const details = warnings.map(w =>
    `Line ${w.line}: barcheck failed at position ${w.position} ` +
    `(bar has the wrong number of beats — off by ${w.position} in 4/4 time)`
  ).join('\n');

  throw new Error(
    `LilyPond barcheck failure — one or more bars have the wrong beat count:\n${details}\n\n` +
    `To fix: count the note and rest durations in the flagged bar(s). ` +
    `In 4/4 time every bar must total exactly 4 beats (16 sixteenth notes). ` +
    `Add or remove a rest/note to correct the total.`
  );
}

/**
 * Post-generation validation: time signatures and pickup measures.
 * Returns { valid, warnings } — warnings are logged but don't block output.
 */
function validateLilypondOutput(lilypondCode) {
  const warnings = [];

  // Count \time occurrences (excluding comments)
  const noComments = lilypondCode.replace(/%[^\n]*/g, '');
  const timeMatches = noComments.match(/\\time\s+\d+\/\d+/g) || [];
  const timeSignaturesCount = timeMatches.length;

  if (timeSignaturesCount > 2) {
    // 2 is expected (one per staff), more means mid-piece changes
    warnings.push(`Multiple \\time signatures detected (${timeSignaturesCount}). Possible mid-piece time change.`);
  }

  // Check for \partial — both hands must match
  const rhMatch = lilypondCode.match(/rightHand\s*=\s*\{([\s\S]*?)\n\}/);
  const lhMatch = lilypondCode.match(/leftHand\s*=\s*\{([\s\S]*?)\n\}/);
  const hasPartial = noComments.includes('\\partial');

  if (hasPartial && rhMatch && lhMatch) {
    const rhPartial = (rhMatch[1].match(/\\partial\s+\S+/) || [null])[0];
    const lhPartial = (lhMatch[1].match(/\\partial\s+\S+/) || [null])[0];

    if (rhPartial && !lhPartial) {
      warnings.push('Pickup (\\partial) in RH but not LH — MIDI may be misaligned.');
    } else if (!rhPartial && lhPartial) {
      warnings.push('Pickup (\\partial) in LH but not RH — MIDI may be misaligned.');
    } else if (rhPartial && lhPartial && rhPartial !== lhPartial) {
      warnings.push(`Mismatched pickups: RH has "${rhPartial}", LH has "${lhPartial}".`);
    }
  }

  // Check \barNumberCheck presence
  const hasBarCheck = noComments.includes('\\barNumberCheck');

  return {
    valid: warnings.length === 0,
    warnings,
    timeSignaturesCount,
    hasPartial,
    hasBarCheck
  };
}

/**
 * PASS A: Build Composer Plan Prompt (constraint-first, NO LilyPond)
 */
function buildComposerPlanPrompt(params) {
  const {
    key,
    bars,
    difficulty,
    style,
    inspiredBy,
    prompt,
    intent,
    motifMode,
    harmonyBudget,
    surpriseType,
    negativeConstraints
  } = params;

  // Default intent if not provided (CRITICAL for quality)
  const composerIntent = intent ||
    "Compose a prelude built from a small idea that resists closure until the final bars.";

  const stylePreset = style ? getStylePreset(style) : null;
  const composer = inspiredBy ? getComposerInspiration(inspiredBy) : null;

  // Determine harmony budget level
  const harmonyLevel = harmonyBudget || (stylePreset?.harmonyBudget) || 'normal';

  const philosophyBlock = getPlanBehavioralOverlay(params);

  let systemPrompt = `You are a composer sketching a brief for a piano prelude. You do NOT write notation yet.
You output a short, impressionistic JSON brief - NOT a detailed structural analysis.

${philosophyBlock}

CRITICAL: Output a SHORT impressionistic brief, not a detailed narrated plan.
The brief should feel like a composer's private sketch - suggestive, not exhaustive.

MANDATORY OUTPUT FORMAT:
{
  "tendencies": ["2-3 vague musical tendencies, e.g. 'harmony drifts between two distant tonal centers'"],
  "emotion": "one sentence describing the emotional stance or character",
  "avoid": "one sentence naming what the piece must NOT do or sound like"
}

Output ONLY the JSON. No explanations, no markdown, no code blocks.`;

  // Add harmony budget constraints
  systemPrompt += `\n\nHARMONY BUDGET: ${harmonyLevel.toUpperCase()}`;

  if (harmonyLevel === 'tight') {
    systemPrompt += `
- Diatonic harmony ONLY
- Maximum ONE borrowed chord allowed
- NO modulation
- State exact cadence plan with roman numerals`;
  } else if (harmonyLevel === 'normal') {
    systemPrompt += `
- One modulation allowed
- 2-3 chromatic events total
- Must state cadence plan with roman numerals`;
  } else if (harmonyLevel === 'rich') {
    systemPrompt += `
- Color harmony allowed
- Still MUST state explicit cadence plan with roman numerals
- Chromatic enrichment must serve structure, not decoration`;
  }

  // Add difficulty-based harmonic rhythm guidance
  if (difficulty === 'beginner') {
    systemPrompt += `\n\nHARMONIC RHYTHM: Slow (~1 change per 2 bars). Harmonic stability is primary.`;
  } else if (difficulty === 'intermediate') {
    systemPrompt += `\n\nHARMONIC RHYTHM: Moderate (1-2 changes per bar). Balance motion with clarity.`;
  } else if (difficulty === 'advanced') {
    systemPrompt += `\n\nHARMONIC RHYTHM: Variable but deliberate. May shift every beat in climactic passages, hold for bars in static passages. The rate of change itself is a compositional tool.`;
  }

  // Add motif mode constraints (OBSESSIVE MODE)
  if (motifMode === true) {
    systemPrompt += `\n\nOBSESSIVE MOTIF MODE (HARD CONSTRAINTS):
- The motif MUST appear every 1-2 bars
- NO new rhythmic cells after bar 8
- Transformations are REQUIRED (not optional)
- Melody derives from motif, accompaniment reacts to it
- Favor memorability and intentional limitation over continuous novelty`;
  }

  // Add structural surprise constraint
  systemPrompt += `\n\nSTRUCTURAL SURPRISE:
Choose EXACTLY ONE surprise from: extra bar, deceptive cadence, phrase truncation, register displacement.
${surpriseType ? `Preference: ${surpriseType}` : 'Default to phrase truncation if unsure.'}
Do NOT add more than one surprise.`;

  // Add style preset constraints
  if (stylePreset) {
    systemPrompt += `\n\nSTYLE CONSTRAINTS: ${stylePreset.name.toUpperCase()}
Phrase Rules: ${stylePreset.constraints.phrase}
Texture: ${stylePreset.constraints.texture}
Harmony: ${stylePreset.constraints.harmony}
Avoid: ${stylePreset.constraints.avoid.join(', ')}`;
  }

  // Add composer inspiration (thinking habits, not sound-alikes)
  if (composer) {
    systemPrompt += `\n\nCOMPOSER THINKING HABIT:
${composer.name}: ${composer.hint}
This describes a way of thinking, not a sound to copy.`;
  }

  // Build user prompt
  let userPrompt = `MUSICAL PROBLEM:\n${composerIntent}

SPECIFICATIONS:
- Key: ${key}
- Bars: ${bars}
- Difficulty: ${difficulty}`;

  if (prompt) {
    userPrompt += `
- User direction: ${compactPromptText(prompt)}`;
  }

  if (negativeConstraints) {
    userPrompt += `\n\nAVOID (HARD CONSTRAINTS):\n${negativeConstraints}`;
  }

  userPrompt += `\n\nGenerate the JSON composer plan now.`;

  return {
    system: systemPrompt,
    user: userPrompt
  };
}

/**
 * PASS A: Generate Composer Plan (JSON only, no LilyPond)
 */
async function generateComposerPlan(params, progressCallback, costTracking) {
  const { system, user } = buildComposerPlanPrompt(params);

  let parseAttempt = 0;

  while (parseAttempt < MAX_PLAN_PARSE_ATTEMPTS) {
    parseAttempt++;

    progressCallback?.({
      message: `Generating composer plan (attempt ${parseAttempt})...`,
      progress: 5 + (parseAttempt * 5)
    });

    try {
      // Safety guard: check API call limit
      checkAPICallLimit(costTracking);

      // Calculate request size
      const requestSize = system.length + user.length;

      const response = await anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 512,
        system: system,
        messages: [{ role: 'user', content: user }]
      });

      let content = response.content[0].text.trim();

      // Track this API call
      trackAPICall(costTracking, 'plan-generate', requestSize, content.length);

      // Strip markdown code blocks if present
      content = content.replace(/^```json?\s*\n?/i, '').replace(/\n?```\s*$/i, '');

      // Parse JSON
      const plan = JSON.parse(content);

      // Validate required fields (new impressionistic brief format)
      const requiredFields = ['tendencies', 'emotion', 'avoid'];
      for (const field of requiredFields) {
        if (!plan[field]) {
          throw new Error(`Missing required field: ${field}`);
        }
      }
      if (!Array.isArray(plan.tendencies) || plan.tendencies.length < 2) {
        throw new Error('tendencies must be an array with at least 2 items');
      }

      console.log('[Composer Plan] ✓ Valid plan generated');
      console.log(JSON.stringify(plan, null, 2));

      return plan;

    } catch (error) {
      console.warn(`[Composer Plan] Parse attempt ${parseAttempt} failed:`, error.message);

      if (parseAttempt >= MAX_PLAN_PARSE_ATTEMPTS) {
        throw new Error(`Failed to generate valid composer plan after ${MAX_PLAN_PARSE_ATTEMPTS} attempts: ${error.message}`);
      }

      // Brief delay before retry
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }
}

/**
 * PASS B: Build LilyPond Generation Prompt (from plan)
 */
function buildLilypondFromPlanPrompt(plan, params) {
  const { key, bars, difficulty } = params;
  const systemPrompt = getComposeSystemPrompt(params);

  const userPrompt = `COMPOSER BRIEF:
${JSON.stringify(plan)}

SPECIFICATIONS:
- Key: ${key}
- Bars: ${bars}
- Difficulty: ${difficulty}

Compose a piano prelude that embodies this brief. The brief gives tendencies and an emotional stance — not a blueprint.
Let the music emerge from these constraints. Do not illustrate them literally.
Honor the "avoid" field strictly.

Output only the complete LilyPond code.`;

  return {
    system: systemPrompt,
    user: userPrompt
  };
}

/**
 * PASS B: Generate LilyPond from Plan
 */
async function generateLilyPondFromPlan(plan, params, conversationHistory = [], costTracking) {
  const { system, user } = buildLilypondFromPlanPrompt(plan, params);

  const messages = conversationHistory.length > 0
    ? conversationHistory
    : [{ role: 'user', content: user }];

  // Safety guard: check API call limit
  checkAPICallLimit(costTracking);

  // Calculate request size
  const requestSize = system.length + messages.reduce((sum, msg) => sum + msg.content.length, 0);

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: 4096,
    system: system,
    messages: messages
  });

  const content = response.content[0].text;

  // Track this API call
  const callType = conversationHistory.length > 0 ? 'repair' : 'generate';
  trackAPICall(costTracking, callType, requestSize, content.length);

  // Extract LilyPond code
  let lilypondCode = content;
  const codeBlockMatch = content.match(/```(?:lilypond)?\n([\s\S]*?)```/);
  if (codeBlockMatch) {
    lilypondCode = codeBlockMatch[1].trim();
  }

  return {
    code: lilypondCode,
    conversationHistory: [...messages, { role: 'assistant', content }]
  };
}

/**
 * OPTIONAL REFINE PASS
 * Uses lightweight haiku model to improve musicality after successful compilation
 */
async function refineLilyPond(lilypondCode, plan, params, costTracking) {
  const modeFlags = getModeFlags(params);
  const modeName = modeFlags.baroque ? 'Baroque mode' : modeFlags.jazz ? 'Jazz mode' : modeFlags.impressionist ? 'Impressionist mode' : modeFlags.classical ? 'Classical mode' : modeFlags.romantic ? 'Romantic mode' : modeFlags.minimal ? 'Minimal mode' : modeFlags.cinematic ? 'Cinematic mode' : 'Organic Time / Anti-Étude mode';

  // Use the SAME behavioral overlay as initial generation
  const systemPrompt = getComposeSystemPrompt(params) + `

REFINE PASS CONSTRAINTS:
- Do NOT change the harmonic plan, form, or bar count
- Do NOT rewrite the music — only make subtle refinements
- Focus on: voice leading smoothness, dynamic shaping, articulation clarity
- Preserve all stylistic/behavioral constraints (${modeName}) — do NOT drift toward exercise phrasing
- Output ONLY the complete refined LilyPond code`;

  const userPrompt = `COMPOSER BRIEF:
${JSON.stringify(plan)}

CURRENT LILYPOND CODE:
${lilypondCode}

Make subtle refinements to improve musicality while preserving ${modeName} constraints. Output only the refined LilyPond code.`;

  // Safety guard: check API call limit
  checkAPICallLimit(costTracking);

  const requestSize = systemPrompt.length + userPrompt.length;

  const response = await anthropic.messages.create({
    model: 'claude-haiku-4-5-20251001',  // Use haiku for cost savings
    max_tokens: 4096,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }]
  });

  const content = response.content[0].text;
  trackAPICall(costTracking, 'refine', requestSize, content.length);

  // Extract LilyPond code
  let refinedCode = content;
  const codeBlockMatch = content.match(/```(?:lilypond)?\n([\s\S]*?)```/);
  if (codeBlockMatch) {
    refinedCode = codeBlockMatch[1].trim();
  }

  return refinedCode;
}

/**
 * TWO-PASS GENERATION WITH REPAIR
 * Pass A: Composer Plan (never regenerated)
 * Pass B: LilyPond from Plan (repaired if needed)
 */
export async function generateWithRepair(params, progressCallback) {
  const {
    key,
    bars,
    difficulty,
    prompt,
    style,
    inspiredBy,
    jobId,
    // New optional parameters
    motifMode = false,
    intent = null,
    negativeConstraints = null,
    surpriseType = null,
    harmonyBudget = null,
    refine = false
  } = params;

  // DRAFT MODE: Cost-saving overrides for development
  const draftMode = process.env.PRELUDE_DRAFT_MODE === 'true';
  let effectiveBars = bars;
  let effectiveHarmonyBudget = harmonyBudget;
  let effectiveSurpriseType = surpriseType;
  let effectiveMaxRepairs = MAX_REPAIR_ATTEMPTS;

  if (draftMode) {
    effectiveBars = Math.min(bars, 12);
    effectiveHarmonyBudget = 'tight';
    effectiveSurpriseType = 'none';
    effectiveMaxRepairs = 2;

    console.log(`[draft-mode] bars capped to ${effectiveBars}, harmony=tight, surprise=none, repair attempts capped to ${effectiveMaxRepairs}`);
  }

  // Build extended spec with draft mode overrides
  const spec = {
    key,
    bars: effectiveBars,
    difficulty,
    prompt,
    style,
    inspiredBy,
    motifMode,
    intent,
    negativeConstraints,
    surpriseType: effectiveSurpriseType,
    harmonyBudget: effectiveHarmonyBudget
  };

  // Detect behavioral mode flags (single source of truth for this job)
  const modeFlags = getModeFlags(spec);
  console.log(`[job ${jobId}] modeFlags=${JSON.stringify(modeFlags)} bars=${effectiveBars} draft=${draftMode}`);

  // Initialize cost tracking
  const costTracking = createCostTracking();

  // Output paths
  const outputDir = path.resolve(__dirname, '../../outputs');
  const basename = `job-${jobId}`;
  const lyPath = path.join(outputDir, `${basename}.ly`);
  const planPath = path.join(outputDir, `${basename}-plan.json`);

  // CHECK CACHE FIRST (immediate cost savings)
  const cacheKey = generateCacheKey(params);
  const cachedResult = getCachedResult(cacheKey);

  if (cachedResult) {
    console.log(`[cache] Returning cached result for job ${jobId}`);
    console.log(`[job ${jobId}] calls=0 inTok≈0 outTok≈0 repairs=0 refine=${refine} draft=${draftMode} cache=hit`);

    progressCallback?.({ message: 'Using cached result...', progress: 100 });

    // Return cached outputs immediately - no API calls needed!
    return {
      success: true,
      outputs: cachedResult.outputs,
      plan: cachedResult.plan || null,
      metrics: {
        humanScore: null,
        humanNotes: null,
        cost: {
          calls: 0,
          approxInputTokens: 0,
          approxOutputTokens: 0,
          callDetails: []
        },
        repairs: 0,
        refine: refine,
        cacheHit: true,
        draftMode
      },
      attempts: 0,
      cacheHit: true,
      draftMode
    };
  }

  console.log(`[cache] MISS - generating new result for job ${jobId}`);

  // PASS A: Generate Composer Plan (ONCE, never regenerated)
  progressCallback?.({ message: 'Creating composer plan...', progress: 5 });

  // Check for cached plan (separate from full output cache)
  let composerPlan = getCachedPlan(cacheKey);

  if (!composerPlan) {
    composerPlan = await generateComposerPlan(spec, progressCallback, costTracking);
  } else {
    console.log(`[cache] Using cached composer plan`);
  }

  // Save plan to file for debugging
  await writeLilyPondFile(JSON.stringify(composerPlan, null, 2), planPath);

  progressCallback?.({ message: 'Composer plan created. Generating notation...', progress: 15 });

  // Build provenance markup for PDF
  const provenanceMarkup = buildProvenanceMarkup({
    key, bars: effectiveBars, difficulty, style, inspiredBy, prompt
  });

  // PASS B: Generate LilyPond from Plan (with repair loop)
  let attempt = 0;
  let conversationHistory = [];
  let lastError = null;
  const regenLog = [];  // Track static-pattern regen reasons

  while (attempt < effectiveMaxRepairs) {
    attempt++;

    try {
      // Generate LilyPond code from plan
      let { code, conversationHistory: newHistory } = await generateLilyPondFromPlan(
        composerPlan,
        spec,
        conversationHistory,
        costTracking
      );

      conversationHistory = newHistory;

      progressCallback?.({
        message: `Attempt ${attempt}: Generated notation, compiling...`,
        progress: 20 + (attempt * 20)
      });

      // Write to file (with provenance block above the score)
      await writeLilyPondFile(injectProvenance(code, provenanceMarkup), lyPath);

      progressCallback?.({
        message: `Attempt ${attempt}: Compiling LilyPond...`,
        progress: 30 + (attempt * 20)
      });

      // Try to compile
      let outputs = await compileLilyPond(lyPath, outputDir);
      assertNoBarcheckFailures(outputs); // barcheck warnings = wrong beat count → repair

      // OPTIONAL REFINE PASS: Improve musicality with lightweight model
      if (refine) {
        progressCallback?.({
          message: 'Refining musicality...',
          progress: 65
        });

        try {
          const refinedCode = await refineLilyPond(code, composerPlan, spec, costTracking);

          // Write refined code to file (with provenance block above the score)
          await writeLilyPondFile(injectProvenance(refinedCode, provenanceMarkup), lyPath);

          progressCallback?.({
            message: 'Recompiling refined notation...',
            progress: 68
          });

          // Recompile with refined code
          const refinedOutputs = await compileLilyPond(lyPath, outputDir);
          assertNoBarcheckFailures(refinedOutputs);

          // Use refined outputs
          outputs = refinedOutputs;
          code = refinedCode;

          console.log('[Refine] ✓ Musicality refinement successful');
        } catch (refineError) {
          console.warn('[Refine] Refinement failed, using original code:', refineError.message);
          // Fall back to original code - already compiled and working
          await writeLilyPondFile(injectProvenance(code, provenanceMarkup), lyPath);
        }
      }

      // POST-CHECK: Detect static patterns and trigger single regen if needed
      const staticIssues = checkStaticPatterns(code);
      if (staticIssues.length > 0 && regenLog.length === 0) {
        // Only attempt one static-pattern regen per job
        regenLog.push({
          timestamp: new Date().toISOString(),
          attempt,
          issues: staticIssues
        });

        console.log('[Static Check] Issues detected:', staticIssues);

        progressCallback?.({
          message: 'Improving musical flow...',
          progress: 68
        });

        try {
          checkAPICallLimit(costTracking);

          const activeMode = modeFlags.baroque ? 'Baroque mode' : modeFlags.jazz ? 'Jazz mode' : modeFlags.impressionist ? 'Impressionist mode' : modeFlags.classical ? 'Classical mode' : modeFlags.romantic ? 'Romantic mode' : modeFlags.minimal ? 'Minimal mode' : modeFlags.cinematic ? 'Cinematic mode' : 'Organic Time / Anti-Étude mode';
          const fixPrompt = `The compiled LilyPond has static-pattern issues:\n${staticIssues.join('\n')}\n\nFix ONLY these issues:\n- Vary the left hand so no 3+ consecutive bars are identical\n- Introduce registral shifts, rhythmic variation, or harmonic change in flagged passages\n- Keep the overall structure, key, and bar count the same\n- Preserve the stylistic/behavioral constraints (${activeMode}). Only fix the flagged passages — do NOT rewrite the piece or drift toward exercise phrasing.\n- Output ONLY the complete corrected LilyPond code.`;

          const fixHistory = [
            ...conversationHistory,
            { role: 'user', content: fixPrompt }
          ];

          const requestSize = fixPrompt.length + conversationHistory.reduce((sum, msg) => sum + msg.content.length, 0);
          const fixResponse = await anthropic.messages.create({
            model: 'claude-sonnet-4-5-20250929',
            max_tokens: 4096,
            messages: fixHistory
          });

          const fixContent = fixResponse.content[0].text;
          trackAPICall(costTracking, 'static-fix', requestSize, fixContent.length);

          let fixedCode = fixContent;
          const fixCodeBlock = fixContent.match(/```(?:lilypond)?\n([\s\S]*?)```/);
          if (fixCodeBlock) {
            fixedCode = fixCodeBlock[1].trim();
          }

          // Write and recompile
          await writeLilyPondFile(injectProvenance(fixedCode, provenanceMarkup), lyPath);
          const fixedOutputs = await compileLilyPond(lyPath, outputDir);
          assertNoBarcheckFailures(fixedOutputs);

          outputs = fixedOutputs;
          code = fixedCode;
          conversationHistory = [...fixHistory, { role: 'assistant', content: fixContent }];

          console.log('[Static Check] ✓ Fix applied successfully');
          regenLog[regenLog.length - 1].resolved = true;
        } catch (fixError) {
          console.warn('[Static Check] Fix failed, keeping original:', fixError.message);
          regenLog[regenLog.length - 1].resolved = false;
          regenLog[regenLog.length - 1].error = fixError.message;
          // Rewrite the original compiled code
          await writeLilyPondFile(injectProvenance(code, provenanceMarkup), lyPath);
        }
      } else if (staticIssues.length === 0) {
        console.log('[Static Check] ✓ No static patterns detected');
      }

      // Post-generation validation: time signatures, pickups, barNumberCheck
      const lyValidation = validateLilypondOutput(code);
      if (lyValidation.warnings.length > 0) {
        console.warn('[LY Validation]', lyValidation.warnings);
      }
      console.log(`[job ${jobId}] validation: timeSigs=${lyValidation.timeSignaturesCount} hasPartial=${lyValidation.hasPartial} barNumberCheck=${lyValidation.hasBarCheck}`);

      progressCallback?.({
        message: 'Compilation successful! Validating MIDI...',
        progress: 70
      });

      // Validate MIDI instrumentation
      if (outputs.midi) {
        const midiPath = outputs.midi;
        const validation = await validateMidi(midiPath);

        if (!validation.valid) {
          console.warn('[MIDI Validation] Failed:', validation.errors);
          console.log(getValidationReport(validation));
        } else {
          console.log('[MIDI Validation] ✓ Valid - Acoustic Grand Piano on multiple channels');
        }

        // Render audio with FluidSynth + Steinway soundfont
        progressCallback?.({
          message: 'Rendering audio with Steinway soundfont...',
          progress: 80
        });

        try {
          const audioOutputs = await renderAudio(midiPath, outputDir);

          if (audioOutputs.wav) {
            outputs.wav = audioOutputs.wav;
          }
          if (audioOutputs.mp3) {
            outputs.mp3 = audioOutputs.mp3;
          }

          progressCallback?.({
            message: 'Audio rendering complete!',
            progress: 95
          });
        } catch (audioError) {
          console.warn('[Audio Rendering] Failed:', audioError.message);
          console.warn('[Audio Rendering] Continuing without audio files...');
        }
      }

      progressCallback?.({
        message: 'Generation complete!',
        progress: 100
      });

      // Analyze human-likeness (optional, display only)
      let metrics = null;
      try {
        metrics = analyzeHumanLikeness(code, composerPlan);
        console.log('[Human Metrics]', JSON.stringify(metrics, null, 2));
      } catch (metricsError) {
        console.warn('[Human Metrics] Analysis failed:', metricsError.message);
        // Continue without metrics - not critical
      }

      // Save regen log if any static-pattern fixes were attempted
      if (regenLog.length > 0) {
        const regenLogPath = path.join(outputDir, `${basename}-regen.json`);
        await writeLilyPondFile(JSON.stringify(regenLog, null, 2), regenLogPath);
        console.log(`[Static Check] Regen log saved to ${basename}-regen.json`);
      }

      // Save to cache for future requests
      const outputsToCache = {
        ly: `${basename}.ly`,
        pdf: path.basename(outputs.pdf),
        midi: outputs.midi ? path.basename(outputs.midi) : null,
        wav: outputs.wav ? path.basename(outputs.wav) : null,
        mp3: outputs.mp3 ? path.basename(outputs.mp3) : null,
        plan: `${basename}-plan.json`
      };

      await saveCacheEntry(cacheKey, outputsToCache, composerPlan);

      // Log cost summary
      console.log(`[job ${jobId}] calls=${costTracking.totalCalls} inTok≈${costTracking.totalInputTokens} outTok≈${costTracking.totalOutputTokens} repairs=${attempt - 1} refine=${refine} draft=${draftMode} cache=miss`);

      // Success! Return outputs with plan and metrics
      return {
        success: true,
        outputs: outputsToCache,
        plan: composerPlan,
        metrics: {
          humanScore: metrics?.humanScore || null,
          humanNotes: metrics?.notes || null,
          cost: {
            calls: costTracking.totalCalls,
            approxInputTokens: costTracking.totalInputTokens,
            approxOutputTokens: costTracking.totalOutputTokens,
            callDetails: costTracking.calls
          },
          repairs: attempt - 1,
          refine: refine,
          cacheHit: false,
          draftMode
        },
        attempts: attempt,
        cacheHit: false,
        draftMode
      };

    } catch (error) {
      lastError = error;

      progressCallback?.({
        message: `Attempt ${attempt}: Compilation failed, repairing notation...`,
        progress: 40 + (attempt * 15)
      });

      if (attempt >= effectiveMaxRepairs) {
        break;
      }

      // REPAIR PROMPT — preserves behavioral constraints
      const activeMode = modeFlags.baroque ? 'Baroque mode' : modeFlags.jazz ? 'Jazz mode' : modeFlags.impressionist ? 'Impressionist mode' : modeFlags.classical ? 'Classical mode' : modeFlags.romantic ? 'Romantic mode' : modeFlags.minimal ? 'Minimal mode' : modeFlags.cinematic ? 'Cinematic mode' : 'Organic Time / Anti-Étude mode';
      const repairPrompt = `You are fixing LilyPond compilation errors.

Task:
- Return a COMPLETE corrected LilyPond file.
- Make the smallest possible changes to fix the compile error.
- Do NOT rewrite the music unless required for correctness.
- Preserve key, time, bar count, and overall structure.
- Preserve the stylistic/behavioral constraints (${activeMode}). Only fix LilyPond syntax, bar counts, and rhythmic completeness.
- If \\barNumberCheck fails, adjust measures to match — do NOT remove \\barNumberCheck.

Constraints:
- LilyPond 2.24+.
- PianoStaff with RH/LH staves.
- No commentary, no explanations, no markdown.

Compiler error:
${error.message}

Current LilyPond:
${code}`;

      conversationHistory = [
        ...conversationHistory,
        { role: 'user', content: repairPrompt }
      ];

      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }

  // All attempts failed
  throw new Error(
    `Failed to generate valid LilyPond after ${effectiveMaxRepairs} attempts${draftMode ? ' (draft mode)' : ''}. Last error: ${lastError?.message || 'Unknown error'}`
  );
}
