/**
 * Two-Pass LilyPond Generation with Composer Planning
 * Pass A: Generate structured composer plan (JSON)
 * Pass B: Generate LilyPond from plan
 */

import Anthropic from '@anthropic-ai/sdk';
import { compileLilyPond, writeLilyPondFile } from './lilypondCompiler.js';
import { getStylePreset, getComposerInspiration } from './stylePresets.js';
import { validateMidi, getValidationReport } from './midiValidator.js';
import { renderAudio } from './audioRenderer.js';
import { analyzeHumanLikeness } from './humanMetrics.js';
import { generateCacheKey, getCachedResult, getCachedPlan, saveCacheEntry } from './cache.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Anthropic client
const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY
});

const MAX_REPAIR_ATTEMPTS = 3;
const MAX_PLAN_PARSE_ATTEMPTS = 2;
const MAX_TOTAL_CLAUDE_CALLS = 10;  // Safety guard: max API calls per job

/**
 * Safety guard: Check if we've exceeded max API calls
 */
function checkAPICallLimit(costTracking) {
  if (costTracking.totalCalls >= MAX_TOTAL_CLAUDE_CALLS) {
    throw new Error(
      `Safety limit exceeded: job reached ${MAX_TOTAL_CLAUDE_CALLS} API calls. ` +
      `This prevents runaway costs. Adjust MAX_TOTAL_CLAUDE_CALLS if needed.`
    );
  }
}

/**
 * Cost tracking helper
 * Approximate tokens: chars / 4 (rough estimate)
 */
function trackAPICall(costTracking, callType, requestChars, responseChars) {
  const approxInputTokens = Math.ceil(requestChars / 4);
  const approxOutputTokens = Math.ceil(responseChars / 4);

  costTracking.calls.push({
    type: callType,
    requestChars,
    responseChars,
    approxInputTokens,
    approxOutputTokens
  });

  costTracking.totalCalls++;
  costTracking.totalInputTokens += approxInputTokens;
  costTracking.totalOutputTokens += approxOutputTokens;
}

/**
 * Initialize cost tracking object
 */
function createCostTracking() {
  return {
    calls: [],
    totalCalls: 0,
    totalInputTokens: 0,
    totalOutputTokens: 0
  };
}

/**
 * Normalize free text to keep prompts concise and token-efficient.
 */
function compactPromptText(text, maxLength = 240) {
  if (!text || typeof text !== 'string') return '';

  const compact = text.replace(/\s+/g, ' ').trim();
  if (compact.length <= maxLength) return compact;

  return compact.slice(0, maxLength - 3).trimEnd() + '...';
}

/**
 * Build provenance markup block for LilyPond PDF.
 * Appears as a small, muted info block above the score.
 */
function buildProvenanceMarkup(params) {
  const { key, bars, difficulty, style, inspiredBy, prompt } = params;

  const year = new Date().getFullYear();
  const diffLabel = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);

  // Escape for LilyPond string literals
  function escapeLy(str) {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  // Truncate prompt if needed
  let shortPrompt = (prompt || '').trim();
  if (shortPrompt.length > 120) {
    shortPrompt = shortPrompt.substring(0, 117).trim() + '...';
  }

  // Get display names for style and composer
  const styleName = style ? (getStylePreset(style)?.name || style) : null;
  const composerName = inspiredBy ? (getComposerInspiration(inspiredBy)?.name || inspiredBy) : null;

  // Build content lines for the markup block
  const lines = [];

  if (shortPrompt) {
    lines.push('"Generated from a natural-language description:"');
    lines.push('\\italic { "' + escapeLy('\u201C' + shortPrompt + '\u201D') + '" }');
    lines.push('\\vspace #0.3');
  }

  lines.push('"Key: ' + escapeLy(key) + ' \u00B7 Bars: ' + bars + ' \u00B7 Difficulty: ' + diffLabel + '"');

  if (styleName) {
    lines.push('"Style: ' + escapeLy(styleName) + '"');
  }
  if (composerName) {
    lines.push('"Inspiration: ' + escapeLy(composerName) + '"');
  }

  lines.push('\\vspace #0.3');
  lines.push('"Generated by Prelude \u00B7 ' + year + '"');

  const indented = lines.map(l => '      ' + l).join('\n');

  return [
    '',
    '\\markup \\fill-line {',
    '  \\center-column {',
    "    \\fontsize #-2 \\with-color #(x11-color 'grey50) \\center-column {",
    indented,
    '    }',
    '    \\vspace #1',
    '  }',
    '}',
    ''
  ].join('\n');
}

/**
 * Inject provenance markup into LilyPond code, before the \\score block.
 */
function injectProvenance(code, provenanceMarkup) {
  const scoreIndex = code.indexOf('\\score');
  if (scoreIndex !== -1) {
    return code.substring(0, scoreIndex) + provenanceMarkup + '\n' + code.substring(scoreIndex);
  }
  // Fallback: prepend after version line
  const versionEnd = code.indexOf('\n');
  if (versionEnd !== -1) {
    return code.substring(0, versionEnd + 1) + provenanceMarkup + '\n' + code.substring(versionEnd + 1);
  }
  return provenanceMarkup + '\n' + code;
}

/**
 * Detect active behavioral mode flags for a given params object.
 * Returns { baroque, organicTime, antiEtude } booleans.
 * Low threshold — better to over-trigger than under-trigger.
 */
export function getModeFlags(params) {
  const { style, inspiredBy, prompt } = params;

  // Baroque detection: check all three sources
  let baroque = false;
  if (style && ['baroque', 'keyboard', 'partita'].includes(style.toLowerCase())) baroque = true;
  if (inspiredBy && inspiredBy.toLowerCase() === 'bach') baroque = true;
  if (prompt) {
    const lower = prompt.toLowerCase();
    const keywords = [
      'bach', 'partita', 'fugue', 'invention', 'baroque', 'contrapuntal',
      'counterpoint', 'prelude and fugue', 'well-tempered', 'toccata',
      'sarabande', 'allemande', 'courante', 'gigue', 'bourrée', 'bourree',
      'gavotte', 'minuet', 'passacaglia', 'chaconne', 'ricercar', 'sinfonia'
    ];
    if (keywords.some(k => lower.includes(k))) baroque = true;
  }

  return {
    baroque,
    organicTime: !baroque,   // default mode when not baroque
    antiEtude: !baroque       // default mode when not baroque
  };
}

/**
 * Get the behavioral overlay string for the current mode.
 * Used by plan, compose, and refine prompts.
 */
function getBehavioralOverlay(params) {
  const modeFlags = getModeFlags(params);
  return modeFlags.baroque ? BAROQUE_COMPOSE_INSTRUCTIONS : DEFAULT_COMPOSE_INSTRUCTIONS;
}

/**
 * Get the plan-phase behavioral overlay (condensed version).
 */
function getPlanBehavioralOverlay(params) {
  const modeFlags = getModeFlags(params);
  return modeFlags.baroque ? BAROQUE_PLAN_INSTRUCTIONS : DEFAULT_PLAN_INSTRUCTIONS;
}

/**
 * Build the full compose/refine system prompt (behavioral overlay + LilyPond template + syntax rules).
 * Single source of truth — used by initial generation AND refine pass.
 */
function getComposeSystemPrompt(params) {
  const modeFlags = getModeFlags(params);
  const overlay = getBehavioralOverlay(params);
  const bars = params.bars || 16;

  const tempoComment = modeFlags.baroque
    ? '% use expressive indications sparingly: con moto, senza rigidità, quasi improvisando'
    : '% use expressive tempo markings (rubato, poco allargando, etc.)';

  return `You are an expert LilyPond engraver and composer. You have received a composer's impressionistic brief — NOT a detailed plan.
Your job is to compose and engrave a finished piano prelude that embodies the brief's tendencies and emotional stance.

${overlay}

REQUIRED LILYPOND STRUCTURE:

\\version "2.24.0"

rightHand = {
  \\clef treble
  \\key [key] \\[mode]
  \\time 4/4
  ${tempoComment}
  % ... music ...
  \\barNumberCheck #${bars + 1}
}

leftHand = {
  \\clef bass
  \\key [key] \\[mode]
  \\time 4/4
  % left hand music — independent voice, not accompaniment
  % ... music ...
  \\barNumberCheck #${bars + 1}
}

\\score {
  <<
    \\new PianoStaff <<
      \\new Staff = "RH" \\with {
        midiInstrument = "acoustic grand"
        midiMinimumVolume = #0.3
        midiMaximumVolume = #0.9
      } {
        \\rightHand
      }

      \\new Staff = "LH" \\with {
        midiInstrument = "acoustic grand"
        midiMinimumVolume = #0.2
        midiMaximumVolume = #0.7
      } {
        \\leftHand
      }
    >>
  >>
  \\layout { }
  \\midi {
    \\tempo 4 = 72
  }
}

BAR COUNT ENFORCEMENT:
- The piece MUST have exactly ${bars} full bars in each hand
- Place \\barNumberCheck #${bars + 1} as the LAST item before the closing brace in BOTH rightHand and leftHand
- If LilyPond warns about a bar number mismatch, fix the measure count — do NOT remove \\barNumberCheck

SYNTAX RULES:
- Articulations come AFTER duration: c'4-> (correct), c'->4 (wrong)
- Use articulations SPARINGLY (max 2-3 per phrase)
- Crescendo/decrescendo must be paired: \\< ... \\!
- Never combine articulations with dynamics: c'16->\\< is INVALID
- Dynamic contour is REQUIRED: include at least one soft marking (pp/p/mp) and one strong marking (mf/f/ff) across the piece
- Use accent language for buildup/power where musically justified: >, ^, or \\sfz (sparingly, not every bar)
- Shape power with hairpins and dynamic contrast; avoid staying at one dynamic level throughout
- Keep each hand physically playable: avoid vertical stacks wider than an octave + third unless explicitly rolled
- Avoid dense pitch clusters and repeated multi-note piles; default to single-note lines or two-note intervals
- Large leaps (> octave) should be occasional, not continuous texture
- All braces must be balanced
- Use \\fermata on notes/rests for hesitation points — not only at cadences
- Do NOT change \\time mid-piece unless explicitly requested
- If using \\partial for pickup, BOTH hands must share the same pickup structure`;
}

/**
 * Baroque/Bach-adjacent behavioral instructions.
 * Replaces the default Core Composition Instructions when Baroque mode is active.
 */
const BAROQUE_PLAN_INSTRUCTIONS = `--- BAROQUE BEHAVIORAL PHILOSOPHY ---

Role: You are composing music that behaves like real written music, not music that demonstrates knowledge of a style.

1. Anti-Pastiche Rule (global, mandatory)
- Do not attempt to "sound like Bach"
- Do not spotlight stylistic features
- Do not explain musical ideas through clear exposition
- If the piece feels like it is referencing Bach rather than needing to exist, revise

2. Motion First, Material Second
- Do NOT clearly introduce a motif at the beginning
- Avoid intervallic cells that can be named or summarized
- Let figuration be the material
- Bach does not present ideas. He moves, and ideas emerge incidentally

3. Continuous figuration is primary
- At least one voice must maintain near-continuous motion
- Avoid block textures, static pedals, or sustained "support" roles
- Motion may thin, but it must not stop unless structurally necessary

4. Harmony as Consequence
- Harmony should feel dragged along by motion, not aimed at
- Tonic arrival should feel incidental or delayed
- If a cadence feels "earned", it is probably too obvious

5. Texture Independence
- Left hand must not act as accompaniment
- Right hand must not act as melody
- Both hands participate in motion and counter-motion

6. Emotional Stance
- Compose as if the piece was not commissioned and does not need approval
- The music should feel indifferent to the listener

7. Default Bias Overrides (AI-specific)
- Actively resist: pastiche signaling, clear exposition, polite endings, even pacing
- When in doubt: choose motion over statement, overlap over clarity

--- END PHILOSOPHY ---`;

const BAROQUE_COMPOSE_INSTRUCTIONS = `--- PRELUDE: BAROQUE BEHAVIORAL INSTRUCTIONS ---

Role: You are composing music that behaves like real written music, not music that demonstrates knowledge of a style.

1. ANTI-PASTICHE RULE (global, mandatory)
Do not attempt to "sound like Bach". Do not spotlight stylistic features.
Do not explain musical ideas through clear exposition.
If the piece feels like it is referencing Bach rather than needing to exist, revise.

2. MOTION FIRST, MATERIAL SECOND
2.1 No motif declaration
- Do not clearly introduce a motif at the beginning
- Avoid intervallic cells that can be named or summarized
- Let figuration be the material
- Bach does not present ideas. He moves, and ideas emerge incidentally.

2.2 Continuous figuration is primary
- At least one voice must maintain near-continuous motion
- Avoid block textures, static pedals, or sustained "support" roles
- Motion may thin, but it must not stop unless structurally necessary
- If the texture pauses to "say something", it is wrong

3. TIME IS HIERARCHICAL, NOT EVEN (critical)
3.1 Meter ≠ felt time
- The written meter may remain constant
- The experienced time must be unequal
- Achieve this through: overlapping voices, suspensions that lean forward, rhythmic inequality, note groupings that resist barlines
- Never treat the barline as an arrival point

3.2 Dance rhetoric without choreography
- If the piece implies a dance meter: accents must be implied not hammered, downbeats must often be softened, energy should flow through the barline
- If MIDI playback sounds square, exaggerate inequality in notation

4. AVOID PLANNED IRREGULARITY
- Do not insert "surprises" by plan
- Do not truncate phrases for effect
- Irregularity must arise from: voice-leading pressure, harmonic necessity, contrapuntal overlap
- Bach's asymmetry is a byproduct, not a feature

5. HARMONY AS CONSEQUENCE, NOT DESTINATION
- Avoid functional cadences as goals
- Harmony should feel dragged along by motion, not aimed at
- Tonic arrival should feel incidental or delayed
- If a cadence feels "earned", it is probably too obvious

6. TEXTURE INDEPENDENCE (hands are not roles)
- Left hand must not act as accompaniment
- Right hand must not act as melody
- Both hands participate in motion and counter-motion
- If one hand exists primarily to support the other, revise

7. TEMPO & TEMPORAL AUTHORITY (Bach-specific)
7.1 No metronomic authority
- Avoid numeric tempos
- Use expressive indications sparingly: con moto, senza rigidità, quasi improvisando
- Time should feel remembered, not enforced

7.2 Rhetorical stretching
- Allow written suspensions and overlaps to imply: hesitation, urgency, overrun
- Do not rely on performer rubato to fix rigid writing

8. ENDINGS: STOP, DON'T CONCLUDE
- Avoid rhetorical "finality"
- Do not slow down to announce the end
- Prefer endings that feel like: motion stopping due to exhaustion, texture thinning until nothing remains, harmonic arrival without ceremony
- If the ending says "this is the end", it is wrong

9. MIDI REALITY CHECK (internal)
- Assume MIDI playback will flatten rhetoric
- Therefore: exaggerate inequality in notation, overemphasize overlaps and suspensions, distrust even rhythms
- Write against the MIDI engine

10. INTERNAL AUTHENTICITY TEST
Before finalizing, silently ask:
- Does this feel like continuous thought?
- Could any section be labeled or summarized?
- Does the music move because it must, or because it was planned?
If it feels planned, revise.

ANCHOR: Compose as if the barline is an inconvenience, the cadence is an accident, and motion is the only truth.

--- END BAROQUE INSTRUCTIONS ---`;

const DEFAULT_PLAN_INSTRUCTIONS = `--- CORE COMPOSITION PHILOSOPHY ---

Role: You are composing a finished musical work, not an exercise, étude, demonstration, or example.
Your goal is to create a piece that feels internally motivated, temporally elastic, and emotionally lived-in.

1. Anti-Exercise Rule (global)
Do not conceive music that clearly demonstrates a technique, announces its structure, or teaches a concept.
If a passage could be labeled ("this is the motif", "this is the sequence"), rethink it.
Music should feel discovered, not explained.

2. Temporal Awareness
- The piece should not feel governed by a single fixed tempo
- At least two sections should feel hesitant, suspended, or temporally unclear
- Phrase endings should stretch, blur, or overlap — not resolve cleanly in time

3. Material Rules
- Do not plan a clearly stated motif at the beginning
- If material recurs, it must be incomplete, obscured, or altered beyond recognition
- Avoid explicit "development" — let ideas decay, not complete

4. Form Rules
- Do not pre-label sections internally
- Avoid tidy proportions — permit asymmetry, extra bars, missing bars
- At least one formal idea must fail to resolve
- The ending does not need to feel justified

5. Left Hand / Texture Autonomy
- Left hand must not behave as a static support system
- LH may drift independently, contradict RH rhythm, introduce motion that never stabilizes

6. Emotional Stance
Compose as if the piece was not commissioned, does not need approval, and may never be heard again.
The music should feel indifferent to the listener, not accommodating.

7. Default Bias Overrides (AI-specific)
Actively resist: symmetry, balance, clear exposition, polite endings, even pacing.
When in doubt: choose ambiguity over clarity, drift over direction, silence over explanation.

--- END PHILOSOPHY ---`;

const DEFAULT_COMPOSE_INSTRUCTIONS = `--- PRELUDE: CORE COMPOSITION INSTRUCTIONS ---

Role: You are composing a finished musical work, not an exercise, étude, demonstration, or example.
Your goal is to create a piece that feels internally motivated, temporally elastic, and emotionally lived-in.

1. ANTI-EXERCISE RULE (global)
Do not write music that: clearly demonstrates a technique, announces its structure, or teaches a concept.
If a passage sounds like it could be labeled ("this is the motif", "this is the sequence"), revise it.
Music should feel discovered, not explained.

2. TEMPORAL BEHAVIOR RULES (critical)
2.1 Tempo is expressive, not numeric
- Avoid a single fixed tempo governing the entire piece
- Prefer expressive tempo markings: rubato, senza rigidità, poco allargando, quasi fermata, tempo sospeso
- Use numeric tempo only if absolutely necessary, and treat it as approximate

2.2 Time must misbehave
- At least two sections per piece must feel hesitant, suspended, or temporally unclear
- Perceived tempo should change via note density, ties across barlines, rhythmic compression or thinning — not via mechanical acceleration
- If a section could be played comfortably to a click track, it is too rigid

2.3 Phrase breathing is mandatory
- Phrase endings should often stretch, blur, or overlap
- Written ritardando/allargando should cross barlines and avoid symmetrical placement
- Do not resolve every phrase cleanly in time

2.4 Fermatas are hesitation, not punctuation
- Use soft fermatas on rests and sustained tones
- Avoid placing fermatas only at cadences
- Fermatas should feel like thought pausing, not arrival

3. FLOW & CONTINUITY RULES
3.1 Avoid grid-based pacing
- Do not distribute events evenly across measures
- Avoid predictable attack patterns
- Allow gestures to trail off, restart mid-thought, or overlap with the next idea

3.2 Density over pulse
- Shape time through texture thickening and thinning
- A section may feel "faster" without the tempo changing

4. MOTIF & MATERIAL RULES
- Do not clearly present a motif at the beginning
- If material recurs, it must be incomplete, obscured, or altered beyond recognition
- Avoid explicit "development" — let ideas decay, not complete
- If the listener can summarize the piece's material easily, it is too explicit

5. FORM RULES
- Do not pre-label sections internally
- Avoid tidy proportions — permit asymmetry, extra bars, missing bars
- At least one formal idea must fail to resolve
- The ending does not need to feel justified

6. LEFT HAND / TEXTURE AUTONOMY
- Left hand must not behave as a static support system
- Avoid long stretches of pedal tones or unchanging open intervals
- LH may drift independently, contradict RH rhythm, introduce motion that never stabilizes

7. EMOTIONAL STANCE (very important)
Compose as if: the piece was not commissioned, does not need approval, and may never be heard again.
The music should feel indifferent to the listener, not accommodating.

8. DEFAULT BIAS OVERRIDES (AI-specific)
Actively resist: symmetry, balance, clear exposition, polite endings, even pacing.
When in doubt: choose ambiguity over clarity, drift over direction, silence over explanation.

9. SUCCESS TEST (internal — check silently before finalizing)
- Does the music feel like it needed to be written?
- Does time feel elastic rather than counted?
- Does anything sound like it's proving competence? If yes, revise.

10. ANCHOR
You are not demonstrating music. You are letting music happen and stopping before it explains itself.

--- END CORE INSTRUCTIONS ---`;

/**
 * Deterministic post-check: detect static LH patterns and harmonic stasis.
 * Returns an array of issue descriptions, or empty array if clean.
 */
function checkStaticPatterns(lilypondCode) {
  const issues = [];

  // Extract left hand content between leftHand = { ... }
  const lhMatch = lilypondCode.match(/leftHand\s*=\s*\{([\s\S]*?)\n\}/);
  if (!lhMatch) return issues;

  const lhContent = lhMatch[1];

  // Normalize: strip comments, collapse whitespace
  const normalized = lhContent
    .replace(/%[^\n]*/g, '')
    .replace(/\\(clef|key|time|bar)\b[^\n]*/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  // Split into bars by barcheck '|' or by rough note groupings
  const bars = normalized.split('|').map(b => b.trim()).filter(b => b.length > 0);

  if (bars.length < 3) return issues;

  // Check for 3+ consecutive identical bars (static LH)
  let consecutiveIdentical = 1;
  for (let i = 1; i < bars.length; i++) {
    if (bars[i] === bars[i - 1]) {
      consecutiveIdentical++;
      if (consecutiveIdentical >= 3) {
        issues.push(`Static left hand: bars ${i - 1}-${i + 1} are identical ("${bars[i].substring(0, 40)}...")`);
        break;
      }
    } else {
      consecutiveIdentical = 1;
    }
  }

  // Check for harmonic stasis: same pitch classes repeated across 4+ bars
  // Extract pitch letters (ignoring octave marks and durations)
  const barPitches = bars.map(bar => {
    const pitches = bar.match(/[a-g](?:is|es|isis|eses)?/g);
    return pitches ? pitches.sort().join(',') : '';
  });

  let consecutiveSamePitches = 1;
  for (let i = 1; i < barPitches.length; i++) {
    if (barPitches[i] && barPitches[i] === barPitches[i - 1]) {
      consecutiveSamePitches++;
      if (consecutiveSamePitches >= 4) {
        issues.push(`Harmonic stasis: left hand uses identical pitch classes for ${consecutiveSamePitches} consecutive bars around bar ${i + 1}`);
        break;
      }
    } else {
      consecutiveSamePitches = 1;
    }
  }

  return issues;
}

/**
 * Post-generation validation: time signatures and pickup measures.
 * Returns { valid, warnings } — warnings are logged but don't block output.
 */
function validateLilypondOutput(lilypondCode) {
  const warnings = [];

  // Count \time occurrences (excluding comments)
  const noComments = lilypondCode.replace(/%[^\n]*/g, '');
  const timeMatches = noComments.match(/\\time\s+\d+\/\d+/g) || [];
  const timeSignaturesCount = timeMatches.length;

  if (timeSignaturesCount > 2) {
    // 2 is expected (one per staff), more means mid-piece changes
    warnings.push(`Multiple \\time signatures detected (${timeSignaturesCount}). Possible mid-piece time change.`);
  }

  // Check for \partial — both hands must match
  const rhMatch = lilypondCode.match(/rightHand\s*=\s*\{([\s\S]*?)\n\}/);
  const lhMatch = lilypondCode.match(/leftHand\s*=\s*\{([\s\S]*?)\n\}/);
  const hasPartial = noComments.includes('\\partial');

  if (hasPartial && rhMatch && lhMatch) {
    const rhPartial = (rhMatch[1].match(/\\partial\s+\S+/) || [null])[0];
    const lhPartial = (lhMatch[1].match(/\\partial\s+\S+/) || [null])[0];

    if (rhPartial && !lhPartial) {
      warnings.push('Pickup (\\partial) in RH but not LH — MIDI may be misaligned.');
    } else if (!rhPartial && lhPartial) {
      warnings.push('Pickup (\\partial) in LH but not RH — MIDI may be misaligned.');
    } else if (rhPartial && lhPartial && rhPartial !== lhPartial) {
      warnings.push(`Mismatched pickups: RH has "${rhPartial}", LH has "${lhPartial}".`);
    }
  }

  // Check \barNumberCheck presence
  const hasBarCheck = noComments.includes('\\barNumberCheck');

  return {
    valid: warnings.length === 0,
    warnings,
    timeSignaturesCount,
    hasPartial,
    hasBarCheck
  };
}

/**
 * PASS A: Build Composer Plan Prompt (constraint-first, NO LilyPond)
 */
function buildComposerPlanPrompt(params) {
  const {
    key,
    bars,
    difficulty,
    style,
    inspiredBy,
    prompt,
    intent,
    motifMode,
    harmonyBudget,
    surpriseType,
    negativeConstraints
  } = params;

  // Default intent if not provided (CRITICAL for quality)
  const composerIntent = intent ||
    "Compose a prelude built from a small idea that resists closure until the final bars.";

  const stylePreset = style ? getStylePreset(style) : null;
  const composer = inspiredBy ? getComposerInspiration(inspiredBy) : null;

  // Determine harmony budget level
  const harmonyLevel = harmonyBudget || (stylePreset?.harmonyBudget) || 'normal';

  const philosophyBlock = getPlanBehavioralOverlay(params);

  let systemPrompt = `You are a composer sketching a brief for a piano prelude. You do NOT write notation yet.
You output a short, impressionistic JSON brief - NOT a detailed structural analysis.

${philosophyBlock}

CRITICAL: Output a SHORT impressionistic brief, not a detailed narrated plan.
The brief should feel like a composer's private sketch - suggestive, not exhaustive.

MANDATORY OUTPUT FORMAT:
{
  "tendencies": ["2-3 vague musical tendencies, e.g. 'harmony drifts between two distant tonal centers'"],
  "emotion": "one sentence describing the emotional stance or character",
  "avoid": "one sentence naming what the piece must NOT do or sound like"
}

Output ONLY the JSON. No explanations, no markdown, no code blocks.`;

  // Add harmony budget constraints
  systemPrompt += `\n\nHARMONY BUDGET: ${harmonyLevel.toUpperCase()}`;

  if (harmonyLevel === 'tight') {
    systemPrompt += `
- Diatonic harmony ONLY
- Maximum ONE borrowed chord allowed
- NO modulation
- State exact cadence plan with roman numerals`;
  } else if (harmonyLevel === 'normal') {
    systemPrompt += `
- One modulation allowed
- 2-3 chromatic events total
- Must state cadence plan with roman numerals`;
  } else if (harmonyLevel === 'rich') {
    systemPrompt += `
- Color harmony allowed
- Still MUST state explicit cadence plan with roman numerals
- Chromatic enrichment must serve structure, not decoration`;
  }

  // Add difficulty-based harmonic rhythm guidance
  if (difficulty === 'beginner') {
    systemPrompt += `\n\nHARMONIC RHYTHM: Slow (~1 change per 2 bars). Harmonic stability is primary.`;
  } else if (difficulty === 'intermediate') {
    systemPrompt += `\n\nHARMONIC RHYTHM: Moderate (1-2 changes per bar). Balance motion with clarity.`;
  } else if (difficulty === 'advanced') {
    systemPrompt += `\n\nHARMONIC RHYTHM: Variable but deliberate. May shift every beat in climactic passages, hold for bars in static passages. The rate of change itself is a compositional tool.`;
  }

  // Add motif mode constraints (OBSESSIVE MODE)
  if (motifMode === true) {
    systemPrompt += `\n\nOBSESSIVE MOTIF MODE (HARD CONSTRAINTS):
- The motif MUST appear every 1-2 bars
- NO new rhythmic cells after bar 8
- Transformations are REQUIRED (not optional)
- Melody derives from motif, accompaniment reacts to it
- Favor memorability and intentional limitation over continuous novelty`;
  }

  // Add structural surprise constraint
  systemPrompt += `\n\nSTRUCTURAL SURPRISE:
Choose EXACTLY ONE surprise from: extra bar, deceptive cadence, phrase truncation, register displacement.
${surpriseType ? `Preference: ${surpriseType}` : 'Default to phrase truncation if unsure.'}
Do NOT add more than one surprise.`;

  // Add style preset constraints
  if (stylePreset) {
    systemPrompt += `\n\nSTYLE CONSTRAINTS: ${stylePreset.name.toUpperCase()}
Phrase Rules: ${stylePreset.constraints.phrase}
Texture: ${stylePreset.constraints.texture}
Harmony: ${stylePreset.constraints.harmony}
Avoid: ${stylePreset.constraints.avoid.join(', ')}`;
  }

  // Add composer inspiration (thinking habits, not sound-alikes)
  if (composer) {
    systemPrompt += `\n\nCOMPOSER THINKING HABIT:
${composer.name}: ${composer.hint}
This describes a way of thinking, not a sound to copy.`;
  }

  // Build user prompt
  let userPrompt = `MUSICAL PROBLEM:\n${composerIntent}

SPECIFICATIONS:
- Key: ${key}
- Bars: ${bars}
- Difficulty: ${difficulty}`;

  if (prompt) {
    userPrompt += `
- User direction: ${compactPromptText(prompt)}`;
  }

  if (negativeConstraints) {
    userPrompt += `\n\nAVOID (HARD CONSTRAINTS):\n${negativeConstraints}`;
  }

  userPrompt += `\n\nGenerate the JSON composer plan now.`;

  return {
    system: systemPrompt,
    user: userPrompt
  };
}

/**
 * PASS A: Generate Composer Plan (JSON only, no LilyPond)
 */
async function generateComposerPlan(params, progressCallback, costTracking) {
  const { system, user } = buildComposerPlanPrompt(params);

  let parseAttempt = 0;

  while (parseAttempt < MAX_PLAN_PARSE_ATTEMPTS) {
    parseAttempt++;

    progressCallback?.({
      message: `Generating composer plan (attempt ${parseAttempt})...`,
      progress: 5 + (parseAttempt * 5)
    });

    try {
      // Safety guard: check API call limit
      checkAPICallLimit(costTracking);

      // Calculate request size
      const requestSize = system.length + user.length;

      const response = await anthropic.messages.create({
        model: 'claude-sonnet-4-5-20250929',
        max_tokens: 512,
        system: system,
        messages: [{ role: 'user', content: user }]
      });

      let content = response.content[0].text.trim();

      // Track this API call
      trackAPICall(costTracking, 'plan-generate', requestSize, content.length);

      // Strip markdown code blocks if present
      content = content.replace(/^```json?\s*\n?/i, '').replace(/\n?```\s*$/i, '');

      // Parse JSON
      const plan = JSON.parse(content);

      // Validate required fields (new impressionistic brief format)
      const requiredFields = ['tendencies', 'emotion', 'avoid'];
      for (const field of requiredFields) {
        if (!plan[field]) {
          throw new Error(`Missing required field: ${field}`);
        }
      }
      if (!Array.isArray(plan.tendencies) || plan.tendencies.length < 2) {
        throw new Error('tendencies must be an array with at least 2 items');
      }

      console.log('[Composer Plan] ✓ Valid plan generated');
      console.log(JSON.stringify(plan, null, 2));

      return plan;

    } catch (error) {
      console.warn(`[Composer Plan] Parse attempt ${parseAttempt} failed:`, error.message);

      if (parseAttempt >= MAX_PLAN_PARSE_ATTEMPTS) {
        throw new Error(`Failed to generate valid composer plan after ${MAX_PLAN_PARSE_ATTEMPTS} attempts: ${error.message}`);
      }

      // Brief delay before retry
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }
}

/**
 * PASS B: Build LilyPond Generation Prompt (from plan)
 */
function buildLilypondFromPlanPrompt(plan, params) {
  const { key, bars, difficulty } = params;
  const systemPrompt = getComposeSystemPrompt(params);

  const userPrompt = `COMPOSER BRIEF:
${JSON.stringify(plan)}

SPECIFICATIONS:
- Key: ${key}
- Bars: ${bars}
- Difficulty: ${difficulty}

Compose a piano prelude that embodies this brief. The brief gives tendencies and an emotional stance — not a blueprint.
Let the music emerge from these constraints. Do not illustrate them literally.
Honor the "avoid" field strictly.

Output only the complete LilyPond code.`;

  return {
    system: systemPrompt,
    user: userPrompt
  };
}

/**
 * PASS B: Generate LilyPond from Plan
 */
async function generateLilyPondFromPlan(plan, params, conversationHistory = [], costTracking) {
  const { system, user } = buildLilypondFromPlanPrompt(plan, params);

  const messages = conversationHistory.length > 0
    ? conversationHistory
    : [{ role: 'user', content: user }];

  // Safety guard: check API call limit
  checkAPICallLimit(costTracking);

  // Calculate request size
  const requestSize = system.length + messages.reduce((sum, msg) => sum + msg.content.length, 0);

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: 4096,
    system: system,
    messages: messages
  });

  const content = response.content[0].text;

  // Track this API call
  const callType = conversationHistory.length > 0 ? 'repair' : 'generate';
  trackAPICall(costTracking, callType, requestSize, content.length);

  // Extract LilyPond code
  let lilypondCode = content;
  const codeBlockMatch = content.match(/```(?:lilypond)?\n([\s\S]*?)```/);
  if (codeBlockMatch) {
    lilypondCode = codeBlockMatch[1].trim();
  }

  return {
    code: lilypondCode,
    conversationHistory: [...messages, { role: 'assistant', content }]
  };
}

/**
 * OPTIONAL REFINE PASS
 * Uses lightweight haiku model to improve musicality after successful compilation
 */
async function refineLilyPond(lilypondCode, plan, params, costTracking) {
  const modeFlags = getModeFlags(params);
  const modeName = modeFlags.baroque ? 'Baroque mode' : 'Organic Time / Anti-Étude mode';

  // Use the SAME behavioral overlay as initial generation
  const systemPrompt = getComposeSystemPrompt(params) + `

REFINE PASS CONSTRAINTS:
- Do NOT change the harmonic plan, form, or bar count
- Do NOT rewrite the music — only make subtle refinements
- Focus on: voice leading smoothness, dynamic shaping, articulation clarity
- Preserve all stylistic/behavioral constraints (${modeName}) — do NOT drift toward exercise phrasing
- Output ONLY the complete refined LilyPond code`;

  const userPrompt = `COMPOSER BRIEF:
${JSON.stringify(plan)}

CURRENT LILYPOND CODE:
${lilypondCode}

Make subtle refinements to improve musicality while preserving ${modeName} constraints. Output only the refined LilyPond code.`;

  // Safety guard: check API call limit
  checkAPICallLimit(costTracking);

  const requestSize = systemPrompt.length + userPrompt.length;

  const response = await anthropic.messages.create({
    model: 'claude-haiku-4-5-20251001',  // Use haiku for cost savings
    max_tokens: 4096,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }]
  });

  const content = response.content[0].text;
  trackAPICall(costTracking, 'refine', requestSize, content.length);

  // Extract LilyPond code
  let refinedCode = content;
  const codeBlockMatch = content.match(/```(?:lilypond)?\n([\s\S]*?)```/);
  if (codeBlockMatch) {
    refinedCode = codeBlockMatch[1].trim();
  }

  return refinedCode;
}

/**
 * TWO-PASS GENERATION WITH REPAIR
 * Pass A: Composer Plan (never regenerated)
 * Pass B: LilyPond from Plan (repaired if needed)
 */
export async function generateWithRepair(params, progressCallback) {
  const {
    key,
    bars,
    difficulty,
    prompt,
    style,
    inspiredBy,
    jobId,
    // New optional parameters
    motifMode = false,
    intent = null,
    negativeConstraints = null,
    surpriseType = null,
    harmonyBudget = null,
    refine = false
  } = params;

  // DRAFT MODE: Cost-saving overrides for development
  const draftMode = process.env.PRELUDE_DRAFT_MODE === 'true';
  let effectiveBars = bars;
  let effectiveHarmonyBudget = harmonyBudget;
  let effectiveSurpriseType = surpriseType;
  let effectiveMaxRepairs = MAX_REPAIR_ATTEMPTS;

  if (draftMode) {
    effectiveBars = Math.min(bars, 12);
    effectiveHarmonyBudget = 'tight';
    effectiveSurpriseType = 'none';
    effectiveMaxRepairs = 2;

    console.log(`[draft-mode] bars capped to ${effectiveBars}, harmony=tight, surprise=none, repair attempts capped to ${effectiveMaxRepairs}`);
  }

  // Build extended spec with draft mode overrides
  const spec = {
    key,
    bars: effectiveBars,
    difficulty,
    prompt,
    style,
    inspiredBy,
    motifMode,
    intent,
    negativeConstraints,
    surpriseType: effectiveSurpriseType,
    harmonyBudget: effectiveHarmonyBudget
  };

  // Detect behavioral mode flags (single source of truth for this job)
  const modeFlags = getModeFlags(spec);
  console.log(`[job ${jobId}] modeFlags=${JSON.stringify(modeFlags)} bars=${effectiveBars} draft=${draftMode}`);

  // Initialize cost tracking
  const costTracking = createCostTracking();

  // Output paths
  const outputDir = path.resolve(__dirname, '../../outputs');
  const basename = `job-${jobId}`;
  const lyPath = path.join(outputDir, `${basename}.ly`);
  const planPath = path.join(outputDir, `${basename}-plan.json`);

  // CHECK CACHE FIRST (immediate cost savings)
  const cacheKey = generateCacheKey(params);
  const cachedResult = getCachedResult(cacheKey);

  if (cachedResult) {
    console.log(`[cache] Returning cached result for job ${jobId}`);
    console.log(`[job ${jobId}] calls=0 inTok≈0 outTok≈0 repairs=0 refine=${refine} draft=${draftMode} cache=hit`);

    progressCallback?.({ message: 'Using cached result...', progress: 100 });

    // Return cached outputs immediately - no API calls needed!
    return {
      success: true,
      outputs: cachedResult.outputs,
      plan: cachedResult.plan || null,
      metrics: {
        humanScore: null,
        humanNotes: null,
        cost: {
          calls: 0,
          approxInputTokens: 0,
          approxOutputTokens: 0,
          callDetails: []
        },
        repairs: 0,
        refine: refine,
        cacheHit: true,
        draftMode
      },
      attempts: 0,
      cacheHit: true,
      draftMode
    };
  }

  console.log(`[cache] MISS - generating new result for job ${jobId}`);

  // PASS A: Generate Composer Plan (ONCE, never regenerated)
  progressCallback?.({ message: 'Creating composer plan...', progress: 5 });

  // Check for cached plan (separate from full output cache)
  let composerPlan = getCachedPlan(cacheKey);

  if (!composerPlan) {
    composerPlan = await generateComposerPlan(spec, progressCallback, costTracking);
  } else {
    console.log(`[cache] Using cached composer plan`);
  }

  // Save plan to file for debugging
  await writeLilyPondFile(JSON.stringify(composerPlan, null, 2), planPath);

  progressCallback?.({ message: 'Composer plan created. Generating notation...', progress: 15 });

  // Build provenance markup for PDF
  const provenanceMarkup = buildProvenanceMarkup({
    key, bars: effectiveBars, difficulty, style, inspiredBy, prompt
  });

  // PASS B: Generate LilyPond from Plan (with repair loop)
  let attempt = 0;
  let conversationHistory = [];
  let lastError = null;
  const regenLog = [];  // Track static-pattern regen reasons

  while (attempt < effectiveMaxRepairs) {
    attempt++;

    try {
      // Generate LilyPond code from plan
      let { code, conversationHistory: newHistory } = await generateLilyPondFromPlan(
        composerPlan,
        spec,
        conversationHistory,
        costTracking
      );

      conversationHistory = newHistory;

      progressCallback?.({
        message: `Attempt ${attempt}: Generated notation, compiling...`,
        progress: 20 + (attempt * 20)
      });

      // Write to file (with provenance block above the score)
      await writeLilyPondFile(injectProvenance(code, provenanceMarkup), lyPath);

      progressCallback?.({
        message: `Attempt ${attempt}: Compiling LilyPond...`,
        progress: 30 + (attempt * 20)
      });

      // Try to compile
      let outputs = await compileLilyPond(lyPath, outputDir);

      // OPTIONAL REFINE PASS: Improve musicality with lightweight model
      if (refine) {
        progressCallback?.({
          message: 'Refining musicality...',
          progress: 65
        });

        try {
          const refinedCode = await refineLilyPond(code, composerPlan, spec, costTracking);

          // Write refined code to file (with provenance block above the score)
          await writeLilyPondFile(injectProvenance(refinedCode, provenanceMarkup), lyPath);

          progressCallback?.({
            message: 'Recompiling refined notation...',
            progress: 68
          });

          // Recompile with refined code
          const refinedOutputs = await compileLilyPond(lyPath, outputDir);

          // Use refined outputs
          outputs = refinedOutputs;
          code = refinedCode;

          console.log('[Refine] ✓ Musicality refinement successful');
        } catch (refineError) {
          console.warn('[Refine] Refinement failed, using original code:', refineError.message);
          // Fall back to original code - already compiled and working
          await writeLilyPondFile(injectProvenance(code, provenanceMarkup), lyPath);
        }
      }

      // POST-CHECK: Detect static patterns and trigger single regen if needed
      const staticIssues = checkStaticPatterns(code);
      if (staticIssues.length > 0 && regenLog.length === 0) {
        // Only attempt one static-pattern regen per job
        regenLog.push({
          timestamp: new Date().toISOString(),
          attempt,
          issues: staticIssues
        });

        console.log('[Static Check] Issues detected:', staticIssues);

        progressCallback?.({
          message: 'Improving musical flow...',
          progress: 68
        });

        try {
          checkAPICallLimit(costTracking);

          const activeMode = modeFlags.baroque ? 'Baroque mode' : 'Organic Time / Anti-Étude mode';
          const fixPrompt = `The compiled LilyPond has static-pattern issues:\n${staticIssues.join('\n')}\n\nFix ONLY these issues:\n- Vary the left hand so no 3+ consecutive bars are identical\n- Introduce registral shifts, rhythmic variation, or harmonic change in flagged passages\n- Keep the overall structure, key, and bar count the same\n- Preserve the stylistic/behavioral constraints (${activeMode}). Only fix the flagged passages — do NOT rewrite the piece or drift toward exercise phrasing.\n- Output ONLY the complete corrected LilyPond code.`;

          const fixHistory = [
            ...conversationHistory,
            { role: 'user', content: fixPrompt }
          ];

          const requestSize = fixPrompt.length + conversationHistory.reduce((sum, msg) => sum + msg.content.length, 0);
          const fixResponse = await anthropic.messages.create({
            model: 'claude-sonnet-4-5-20250929',
            max_tokens: 4096,
            messages: fixHistory
          });

          const fixContent = fixResponse.content[0].text;
          trackAPICall(costTracking, 'static-fix', requestSize, fixContent.length);

          let fixedCode = fixContent;
          const fixCodeBlock = fixContent.match(/```(?:lilypond)?\n([\s\S]*?)```/);
          if (fixCodeBlock) {
            fixedCode = fixCodeBlock[1].trim();
          }

          // Write and recompile
          await writeLilyPondFile(injectProvenance(fixedCode, provenanceMarkup), lyPath);
          const fixedOutputs = await compileLilyPond(lyPath, outputDir);

          outputs = fixedOutputs;
          code = fixedCode;
          conversationHistory = [...fixHistory, { role: 'assistant', content: fixContent }];

          console.log('[Static Check] ✓ Fix applied successfully');
          regenLog[regenLog.length - 1].resolved = true;
        } catch (fixError) {
          console.warn('[Static Check] Fix failed, keeping original:', fixError.message);
          regenLog[regenLog.length - 1].resolved = false;
          regenLog[regenLog.length - 1].error = fixError.message;
          // Rewrite the original compiled code
          await writeLilyPondFile(injectProvenance(code, provenanceMarkup), lyPath);
        }
      } else if (staticIssues.length === 0) {
        console.log('[Static Check] ✓ No static patterns detected');
      }

      // Post-generation validation: time signatures, pickups, barNumberCheck
      const lyValidation = validateLilypondOutput(code);
      if (lyValidation.warnings.length > 0) {
        console.warn('[LY Validation]', lyValidation.warnings);
      }
      console.log(`[job ${jobId}] validation: timeSigs=${lyValidation.timeSignaturesCount} hasPartial=${lyValidation.hasPartial} barNumberCheck=${lyValidation.hasBarCheck}`);

      progressCallback?.({
        message: 'Compilation successful! Validating MIDI...',
        progress: 70
      });

      // Validate MIDI instrumentation
      if (outputs.midi) {
        const midiPath = outputs.midi;
        const validation = await validateMidi(midiPath);

        if (!validation.valid) {
          console.warn('[MIDI Validation] Failed:', validation.errors);
          console.log(getValidationReport(validation));
        } else {
          console.log('[MIDI Validation] ✓ Valid - Acoustic Grand Piano on multiple channels');
        }

        // Render audio with FluidSynth + Steinway soundfont
        progressCallback?.({
          message: 'Rendering audio with Steinway soundfont...',
          progress: 80
        });

        try {
          const audioOutputs = await renderAudio(midiPath, outputDir, {
            generateMP3: true
          });

          if (audioOutputs.wav) {
            outputs.wav = audioOutputs.wav;
          }
          if (audioOutputs.mp3) {
            outputs.mp3 = audioOutputs.mp3;
          }

          progressCallback?.({
            message: 'Audio rendering complete!',
            progress: 95
          });
        } catch (audioError) {
          console.warn('[Audio Rendering] Failed:', audioError.message);
          console.warn('[Audio Rendering] Continuing without audio files...');
        }
      }

      progressCallback?.({
        message: 'Generation complete!',
        progress: 100
      });

      // Analyze human-likeness (optional, display only)
      let metrics = null;
      try {
        metrics = analyzeHumanLikeness(code, composerPlan);
        console.log('[Human Metrics]', JSON.stringify(metrics, null, 2));
      } catch (metricsError) {
        console.warn('[Human Metrics] Analysis failed:', metricsError.message);
        // Continue without metrics - not critical
      }

      // Save regen log if any static-pattern fixes were attempted
      if (regenLog.length > 0) {
        const regenLogPath = path.join(outputDir, `${basename}-regen.json`);
        await writeLilyPondFile(JSON.stringify(regenLog, null, 2), regenLogPath);
        console.log(`[Static Check] Regen log saved to ${basename}-regen.json`);
      }

      // Save to cache for future requests
      const outputsToCache = {
        ly: `${basename}.ly`,
        pdf: path.basename(outputs.pdf),
        midi: outputs.midi ? path.basename(outputs.midi) : null,
        wav: outputs.wav ? path.basename(outputs.wav) : null,
        mp3: outputs.mp3 ? path.basename(outputs.mp3) : null,
        plan: `${basename}-plan.json`
      };

      await saveCacheEntry(cacheKey, outputsToCache, composerPlan);

      // Log cost summary
      console.log(`[job ${jobId}] calls=${costTracking.totalCalls} inTok≈${costTracking.totalInputTokens} outTok≈${costTracking.totalOutputTokens} repairs=${attempt - 1} refine=${refine} draft=${draftMode} cache=miss`);

      // Success! Return outputs with plan and metrics
      return {
        success: true,
        outputs: outputsToCache,
        plan: composerPlan,
        metrics: {
          humanScore: metrics?.humanScore || null,
          humanNotes: metrics?.notes || null,
          cost: {
            calls: costTracking.totalCalls,
            approxInputTokens: costTracking.totalInputTokens,
            approxOutputTokens: costTracking.totalOutputTokens,
            callDetails: costTracking.calls
          },
          repairs: attempt - 1,
          refine: refine,
          cacheHit: false,
          draftMode
        },
        attempts: attempt,
        cacheHit: false,
        draftMode
      };

    } catch (error) {
      lastError = error;

      progressCallback?.({
        message: `Attempt ${attempt}: Compilation failed, repairing notation...`,
        progress: 40 + (attempt * 15)
      });

      if (attempt >= effectiveMaxRepairs) {
        break;
      }

      // REPAIR PROMPT — preserves behavioral constraints
      const activeMode = modeFlags.baroque ? 'Baroque mode' : 'Organic Time / Anti-Étude mode';
      const repairPrompt = `You are fixing LilyPond compilation errors.

Task:
- Return a COMPLETE corrected LilyPond file.
- Make the smallest possible changes to fix the compile error.
- Do NOT rewrite the music unless required for correctness.
- Preserve key, time, bar count, and overall structure.
- Preserve the stylistic/behavioral constraints (${activeMode}). Only fix LilyPond syntax, bar counts, and rhythmic completeness.
- If \\barNumberCheck fails, adjust measures to match — do NOT remove \\barNumberCheck.

Constraints:
- LilyPond 2.24+.
- PianoStaff with RH/LH staves.
- No commentary, no explanations, no markdown.

Compiler error:
${error.message}

Current LilyPond:
${code}`;

      conversationHistory = [
        ...conversationHistory,
        { role: 'user', content: repairPrompt }
      ];

      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  }

  // All attempts failed
  throw new Error(
    `Failed to generate valid LilyPond after ${effectiveMaxRepairs} attempts${draftMode ? ' (draft mode)' : ''}. Last error: ${lastError?.message || 'Unknown error'}`
  );
}
